const { PrismaClient } = require('@prisma/client');
const prisma = new PrismaClient();

const documentCatalog = [
  {
    id: 'client-report',
    code: 'CLI-REP-001',
    internalCode: 'CLI-REP-01',
    name: 'مستند تقرير عن عميل',
    description: 'تقرير شامل يحتوي على معلومات محددة وتفصيلية عن العميل',
    defaultSize: 'A4',
    defaultOrientation: 'portrait',
    supportedModes: ['manual', 'auto', 'ai'],
    category: 'تقارير عامة',
    subcategory: 'تقارير عملاء',
    supportsGeneration: true,
    supportsCopy: true,
    supportsAI: true,
    readinessLevel: 'عالية',
    improvementStatus: 'مستقر',
    priority: 'عالية',
    status: 'نشطة',
    usageCount: 0,
    lastUsedAt: '2026-05-16',
    createdAt: '2026-05-16',
    updatedAt: '2026-05-16',
    isAiSuggested: true,
    author: 'النظام',
    responsibleName: 'النظام',
    usageConstraints: {
      typeConditions: [],
      typePriority: 1,
      templateConditions: [],
      defaultTemplateId: 'default',
      forceManualReview: false,
      logicType: 'إلزامية'
    },
    officialCode: '004',
    officialCodeMode: 'numeric',
    officeCode: '1004',
    officeCodeMode: 'numeric',
    codeDisplayPriority: 'official',
    documentStyle: 'official-numbered-formal',
    mainCategory: 'تقارير الإدارة',
    subCategory: 'تقارير عملاء',
    mainCategoryCode: 'MGT',
    subCategoryCode: 'MGT-CLI',
    requirements: [],
    defaultBlocks: []
  },
  {
    id: 'property-ownership-document',
    code: 'PROP-OWN-001',
    internalCode: 'PROP-OWN-01',
    name: 'وثيقة ملكية محددة',
    description: 'مستند يثبت ويوضح تفاصيل وثيقة ملكية محددة',
    defaultSize: 'A4',
    defaultOrientation: 'portrait',
    supportedModes: ['manual', 'auto', 'ai'],
    category: 'مستندات قانونية',
    subcategory: 'وثائق ملكية',
    supportsGeneration: true,
    supportsCopy: true,
    supportsAI: true,
    readinessLevel: 'عالية',
    improvementStatus: 'مستقر',
    priority: 'عالية',
    status: 'نشطة',
    usageCount: 0,
    lastUsedAt: '2026-05-16',
    createdAt: '2026-05-16',
    updatedAt: '2026-05-16',
    isAiSuggested: true,
    author: 'النظام',
    responsibleName: 'النظام',
    usageConstraints: {
      typeConditions: [],
      typePriority: 1,
      templateConditions: [],
      defaultTemplateId: 'default',
      forceManualReview: false,
      logicType: 'إلزامية'
    },
    officialCode: '005',
    officialCodeMode: 'numeric',
    officeCode: '1005',
    officeCodeMode: 'numeric',
    codeDisplayPriority: 'official',
    documentStyle: 'official-numbered-formal',
    mainCategory: 'مستندات قانونية',
    subCategory: 'وثائق ملكية',
    mainCategoryCode: 'LEG',
    subCategoryCode: 'LEG-PROP',
    requirements: [],
    defaultBlocks: []
  },
  {
    id: 'client-financial-report',
    code: 'FIN-CLI-001',
    internalCode: 'FIN-CLI-01',
    name: 'تقرير عن تفاصيل مالية لعميل محدد',
    description: 'تقرير يعرض التفاصيل والحركات المالية الخاصة بعميل محدد',
    defaultSize: 'A4',
    defaultOrientation: 'portrait',
    supportedModes: ['manual', 'auto', 'ai'],
    category: 'تقارير مالية',
    subcategory: 'حسابات عملاء',
    supportsGeneration: true,
    supportsCopy: true,
    supportsAI: true,
    readinessLevel: 'عالية',
    improvementStatus: 'مستقر',
    priority: 'عالية',
    status: 'نشطة',
    usageCount: 0,
    lastUsedAt: '2026-05-16',
    createdAt: '2026-05-16',
    updatedAt: '2026-05-16',
    isAiSuggested: true,
    author: 'النظام',
    responsibleName: 'النظام',
    usageConstraints: {
      typeConditions: [],
      typePriority: 1,
      templateConditions: [],
      defaultTemplateId: 'default',
      forceManualReview: false,
      logicType: 'إلزامية'
    },
    officialCode: '006',
    officialCodeMode: 'numeric',
    officeCode: '1006',
    officeCodeMode: 'numeric',
    codeDisplayPriority: 'official',
    documentStyle: 'official-numbered-formal',
    mainCategory: 'تقارير مالية',
    subCategory: 'حسابات عملاء',
    mainCategoryCode: 'FIN',
    subCategoryCode: 'FIN-CLI',
    requirements: [],
    defaultBlocks: []
  },
  {
    id: 'transaction-financial-report',
    code: 'FIN-TX-001',
    internalCode: 'FIN-TX-01',
    name: 'تقرير عن تفاصيل مالية لمعاملة محددة',
    description: 'تقرير يعرض الدفعات والبيانات المالية المتعلقة بمعاملة محددة',
    defaultSize: 'A4',
    defaultOrientation: 'portrait',
    supportedModes: ['manual', 'auto', 'ai'],
    category: 'تقارير مالية',
    subcategory: 'مالية معاملات',
    supportsGeneration: true,
    supportsCopy: true,
    supportsAI: true,
    readinessLevel: 'عالية',
    improvementStatus: 'مستقر',
    priority: 'عالية',
    status: 'نشطة',
    usageCount: 0,
    lastUsedAt: '2026-05-16',
    createdAt: '2026-05-16',
    updatedAt: '2026-05-16',
    isAiSuggested: true,
    author: 'النظام',
    responsibleName: 'النظام',
    usageConstraints: {
      typeConditions: [],
      typePriority: 1,
      templateConditions: [],
      defaultTemplateId: 'default',
      forceManualReview: false,
      logicType: 'إلزامية'
    },
    officialCode: '007',
    officialCodeMode: 'numeric',
    officeCode: '1007',
    officeCodeMode: 'numeric',
    codeDisplayPriority: 'official',
    documentStyle: 'official-numbered-formal',
    mainCategory: 'تقارير مالية',
    subCategory: 'مالية معاملات',
    mainCategoryCode: 'FIN',
    subCategoryCode: 'FIN-TX',
    requirements: [],
    defaultBlocks: []
  },
  {
    id: 'client-projects-financial-report',
    code: 'FIN-PROJ-001',
    internalCode: 'FIN-PROJ-01',
    name: 'تقرير عن تفاصيل مالية لجميع مشاريع عميل محدد',
    description: 'تقرير يوضح الحالة المالية المجمعة والتفصيلية لجميع مشاريع العميل',
    defaultSize: 'A4',
    defaultOrientation: 'portrait',
    supportedModes: ['manual', 'auto', 'ai'],
    category: 'تقارير مالية',
    subcategory: 'مالية مشاريع',
    supportsGeneration: true,
    supportsCopy: true,
    supportsAI: true,
    readinessLevel: 'عالية',
    improvementStatus: 'مستقر',
    priority: 'عالية',
    status: 'نشطة',
    usageCount: 0,
    lastUsedAt: '2026-05-16',
    createdAt: '2026-05-16',
    updatedAt: '2026-05-16',
    isAiSuggested: true,
    author: 'النظام',
    responsibleName: 'النظام',
    usageConstraints: {
      typeConditions: [],
      typePriority: 1,
      templateConditions: [],
      defaultTemplateId: 'default',
      forceManualReview: false,
      logicType: 'إلزامية'
    },
    officialCode: '008',
    officialCodeMode: 'numeric',
    officeCode: '1008',
    officeCodeMode: 'numeric',
    codeDisplayPriority: 'official',
    documentStyle: 'official-numbered-formal',
    mainCategory: 'تقارير مالية',
    subCategory: 'مالية مشاريع',
    mainCategoryCode: 'FIN',
    subCategoryCode: 'FIN-PROJ',
    requirements: [],
    defaultBlocks: []
  },
  {
    id: 'employee-tasks-report',
    code: 'HR-TSK-001',
    internalCode: 'HR-TSK-01',
    name: 'تقرير عن المهام الموكلة إلى موظف محدد خلال مدة معينة',
    description: 'تقرير يسرد كافة المهام والتكاليف الموكلة لموظف خلال فترة محددة',
    defaultSize: 'A4',
    defaultOrientation: 'portrait',
    supportedModes: ['manual', 'auto', 'ai'],
    category: 'تقارير الموارد البشرية',
    subcategory: 'متابعة مهام',
    supportsGeneration: true,
    supportsCopy: true,
    supportsAI: true,
    readinessLevel: 'عالية',
    improvementStatus: 'مستقر',
    priority: 'عالية',
    status: 'نشطة',
    usageCount: 0,
    lastUsedAt: '2026-05-16',
    createdAt: '2026-05-16',
    updatedAt: '2026-05-16',
    isAiSuggested: true,
    author: 'النظام',
    responsibleName: 'النظام',
    usageConstraints: {
      typeConditions: [],
      typePriority: 1,
      templateConditions: [],
      defaultTemplateId: 'default',
      forceManualReview: false,
      logicType: 'إلزامية'
    },
    officialCode: '009',
    officialCodeMode: 'numeric',
    officeCode: '1009',
    officeCodeMode: 'numeric',
    codeDisplayPriority: 'official',
    documentStyle: 'official-numbered-formal',
    mainCategory: 'موارد بشرية',
    subCategory: 'متابعة مهام',
    mainCategoryCode: 'HR',
    subCategoryCode: 'HR-TSK',
    requirements: [],
    defaultBlocks: []
  },
  {
    id: 'employee-performance-report',
    code: 'HR-PERF-001',
    internalCode: 'HR-PERF-01',
    name: 'تقرير عن أداء موظف',
    description: 'تقرير تقييم شامل لأداء وإنتاجية الموظف',
    defaultSize: 'A4',
    defaultOrientation: 'portrait',
    supportedModes: ['manual', 'auto', 'ai'],
    category: 'تقارير الموارد البشرية',
    subcategory: 'تقييم أداء',
    supportsGeneration: true,
    supportsCopy: true,
    supportsAI: true,
    readinessLevel: 'عالية',
    improvementStatus: 'مستقر',
    priority: 'عالية',
    status: 'نشطة',
    usageCount: 0,
    lastUsedAt: '2026-05-16',
    createdAt: '2026-05-16',
    updatedAt: '2026-05-16',
    isAiSuggested: true,
    author: 'النظام',
    responsibleName: 'النظام',
    usageConstraints: {
      typeConditions: [],
      typePriority: 1,
      templateConditions: [],
      defaultTemplateId: 'default',
      forceManualReview: false,
      logicType: 'إلزامية'
    },
    officialCode: '010',
    officialCodeMode: 'numeric',
    officeCode: '1010',
    officeCodeMode: 'numeric',
    codeDisplayPriority: 'official',
    documentStyle: 'official-numbered-formal',
    mainCategory: 'موارد بشرية',
    subCategory: 'تقييم أداء',
    mainCategoryCode: 'HR',
    subCategoryCode: 'HR-PERF',
    requirements: [],
    defaultBlocks: []
  },
  {
    id: 'employee-attendance-report',
    code: 'HR-ATT-001',
    internalCode: 'HR-ATT-01',
    name: 'تقرير عن حضور موظف خلال مدة محددة',
    description: 'تقرير يوضح سجلات الدوام والحضور والانصراف للموظف خلال فترة',
    defaultSize: 'A4',
    defaultOrientation: 'portrait',
    supportedModes: ['manual', 'auto', 'ai'],
    category: 'تقارير الموارد البشرية',
    subcategory: 'حضور وانصراف',
    supportsGeneration: true,
    supportsCopy: true,
    supportsAI: true,
    readinessLevel: 'عالية',
    improvementStatus: 'مستقر',
    priority: 'عالية',
    status: 'نشطة',
    usageCount: 0,
    lastUsedAt: '2026-05-16',
    createdAt: '2026-05-16',
    updatedAt: '2026-05-16',
    isAiSuggested: true,
    author: 'النظام',
    responsibleName: 'النظام',
    usageConstraints: {
      typeConditions: [],
      typePriority: 1,
      templateConditions: [],
      defaultTemplateId: 'default',
      forceManualReview: false,
      logicType: 'إلزامية'
    },
    officialCode: '011',
    officialCodeMode: 'numeric',
    officeCode: '1011',
    officeCodeMode: 'numeric',
    codeDisplayPriority: 'official',
    documentStyle: 'official-numbered-formal',
    mainCategory: 'موارد بشرية',
    subCategory: 'حضور وانصراف',
    mainCategoryCode: 'HR',
    subCategoryCode: 'HR-ATT',
    requirements: [],
    defaultBlocks: []
  },
  {
    id: 'transaction-status-report',
    code: 'TX-STAT-001',
    internalCode: 'TX-STAT-01',
    name: 'تقرير عن حالة معاملة',
    description: 'تقرير يوضح حالة المعاملة بكافة تفريعاتها (مختصر، تفصيلي مع بيانات مالية، أو بدون بيانات مالية)',
    defaultSize: 'A4',
    defaultOrientation: 'portrait',
    supportedModes: ['manual', 'auto', 'ai'],
    category: 'مستندات معاملات',
    subcategory: 'تقارير الحالة',
    supportsGeneration: true,
    supportsCopy: true,
    supportsAI: true,
    readinessLevel: 'عالية',
    improvementStatus: 'مستقر',
    priority: 'عالية',
    status: 'نشطة',
    usageCount: 0,
    lastUsedAt: '2026-05-16',
    createdAt: '2026-05-16',
    updatedAt: '2026-05-16',
    isAiSuggested: true,
    author: 'النظام',
    responsibleName: 'النظام',
    usageConstraints: {
      typeConditions: [],
      typePriority: 1,
      templateConditions: [],
      defaultTemplateId: 'default',
      forceManualReview: false,
      logicType: 'إلزامية'
    },
    officialCode: '003',
    officialCodeMode: 'numeric',
    officeCode: '1003',
    officeCodeMode: 'numeric',
    codeDisplayPriority: 'official',
    documentStyle: 'official-numbered-formal',
    mainCategory: 'مستندات معاملات',
    subCategory: 'تقارير الإنجاز والحالة',
    mainCategoryCode: 'TRX',
    subCategoryCode: 'TRX-STAT',
    requirements: [],
    defaultBlocks: [] 
  },
  {
    id: 'technical-report',
    code: 'TR-001',
    internalCode: 'TECH-REP-01',
    name: 'التقرير الفني',
    description: 'تقرير فني هندسي مفصل',
    defaultSize: 'A4',
    defaultOrientation: 'portrait',
    supportedModes: ['manual', 'auto', 'ai'],
    category: 'مستندات فنية',
    subcategory: 'تقارير هندسية',
    supportsGeneration: true,
    supportsCopy: true,
    supportsAI: true,
    readinessLevel: 'عالية',
    improvementStatus: 'مستقر',
    priority: 'عالية',
    status: 'نشطة',
    usageCount: 5,
    lastUsedAt: '2026-04-05',
    createdAt: '2024-01-15',
    updatedAt: '2026-04-01',
    isAiSuggested: true,
    author: 'م. فهد العتيبي',
    responsibleName: 'سارة خالد',
    usageConstraints: {
      typeConditions: [],
      typePriority: 1,
      templateConditions: [],
      defaultTemplateId: 'default',
      forceManualReview: false,
      logicType: 'إلزامية'
    },
    officialCode: '001',
    officialCodeMode: 'numeric',
    officeCode: '1001',
    officeCodeMode: 'numeric',
    codeDisplayPriority: 'official',
    documentStyle: 'official-numbered-formal',
    mainCategory: 'مستندات معاملات',
    subCategory: 'تقارير هندسية',
    mainCategoryCode: 'TRX',
    subCategoryCode: 'TRX-REP',
    requirements: [],
    defaultBlocks: [] 
  },
  {
    id: 'survey-report',
    code: 'SR-001',
    internalCode: 'SURV-REP-01',
    name: 'التقرير المساحي',
    description: 'تقرير مساحي مفصل',
    defaultSize: 'A3',
    defaultOrientation: 'landscape',
    supportedModes: ['manual', 'auto', 'ai'],
    category: 'مستندات مساحية',
    subcategory: 'تقارير مساحية',
    supportsGeneration: true,
    supportsCopy: true,
    supportsAI: true,
    readinessLevel: 'عالية',
    improvementStatus: 'مستقر',
    priority: 'عالية',
    status: 'نشطة',
    usageCount: 3,
    lastUsedAt: '2026-04-04',
    author: 'سارة خالد',
    responsibleName: 'م. فهد العتيبي',
    usageConstraints: {
      typeConditions: [],
      typePriority: 1,
      templateConditions: [],
      defaultTemplateId: 'default',
      forceManualReview: false,
      logicType: 'إلزامية'
    },
    officialCode: '002',
    officialCodeMode: 'numeric',
    officeCode: '1002',
    officeCodeMode: 'numeric',
    codeDisplayPriority: 'official',
    documentStyle: 'official-numbered-formal',
    mainCategory: 'مستندات مساحية',
    subCategory: 'مستندات رفع',
    mainCategoryCode: 'SURV-01',
    subCategoryCode: 'SURV-01-01',
    requirements: [],
    defaultBlocks: [] 
  },
  {
    id: 'ownership-deed',
    code: 'OD-001',
    internalCode: 'OWN-DEED-01',
    name: 'صك الملكية',
    description: 'وثيقة صك الملكية',
    defaultSize: 'A4',
    defaultOrientation: 'portrait',
    supportedModes: ['manual'],
    category: 'مستندات ملكية وهوية',
    subcategory: 'صكوك',
    supportsGeneration: false,
    supportsCopy: true,
    supportsAI: false,
    readinessLevel: 'عالية',
    improvementStatus: 'مستقر',
    priority: 'عالية',
    status: 'نشطة',
    usageCount: 10,
    lastUsedAt: '2026-04-03',
    author: 'أحمد محمد',
    usageConstraints: {
      typeConditions: [],
      typePriority: 1,
      templateConditions: [],
      defaultTemplateId: 'default',
      forceManualReview: false,
      logicType: 'إلزامية'
    },
    officialCode: '003',
    officialCodeMode: 'numeric',
    officeCode: '1003',
    officeCodeMode: 'numeric',
    codeDisplayPriority: 'official',
    documentStyle: 'official-numbered-formal',
    mainCategory: 'مستندات ملكية',
    subCategory: 'صكوك ووثائق ملكية',
    mainCategoryCode: 'OWN-01',
    subCategoryCode: 'OWN-01-01',
    defaultBlocks: []
  },
  {
    id: 'power-release',
    code: 'DOC-134',
    internalCode: 'PWR-REL-01',
    name: 'مستند إطلاق تيار',
    description: 'مستند إطلاق التيار الكهربائي',
    defaultSize: 'A4',
    defaultOrientation: 'portrait',
    supportedModes: ['manual', 'auto'],
    category: 'مستندات تصفيات وخدمات',
    subcategory: 'كهرباء',
    supportsGeneration: true,
    supportsCopy: true,
    supportsAI: false,
    readinessLevel: 'متوسطة',
    improvementStatus: 'تحت التطوير',
    priority: 'متوسطة',
    usageCount: 0,
    lastUsedAt: '2026-04-05',
    usageConstraints: {
      typeConditions: [],
      typePriority: 1,
      templateConditions: [],
      defaultTemplateId: 'default',
      forceManualReview: false,
      logicType: 'إلزامية'
    },
    officialCode: '134',
    officialCodeMode: 'numeric',
    officeCode: '1134',
    officeCodeMode: 'numeric',
    codeDisplayPriority: 'official',
    documentStyle: 'official-numbered-formal',
    mainCategory: 'مستندات تصفيات وخدمات',
    subCategory: 'كهرباء',
    mainCategoryCode: 'PWR-01',
    subCategoryCode: 'PWR-01-01',
    defaultBlocks: []
  },
  {
    id: 'site-plan',
    code: 'SP-001',
    internalCode: 'SITE-PLAN-01',
    name: 'مخطط الموقع',
    description: 'مخطط الموقع العام',
    defaultSize: 'A3',
    defaultOrientation: 'landscape',
    supportedModes: ['manual', 'auto'],
    category: 'مستندات الموقع والخرائط',
    subcategory: 'مخططات',
    supportsGeneration: true,
    supportsCopy: true,
    supportsAI: false,
    readinessLevel: 'متوسطة',
    improvementStatus: 'تحت التطوير',
    priority: 'متوسطة',
    usageCount: 2,
    lastUsedAt: '2026-04-02',
    officialCode: '135',
    officialCodeMode: 'numeric',
    officeCode: '1135',
    officeCodeMode: 'numeric',
    codeDisplayPriority: 'official',
    documentStyle: 'official-numbered-formal',
    mainCategory: 'مستندات الموقع والخرائط',
    subCategory: 'مخططات',
    mainCategoryCode: 'SITE-01',
    subCategoryCode: 'SITE-01-01',
    defaultBlocks: []
  },
  {
    id: 'id-card',
    code: 'ID-001',
    internalCode: 'ID-CARD-01',
    name: 'الهوية الوطنية',
    description: 'صورة الهوية الوطنية',
    defaultSize: 'A4',
    defaultOrientation: 'portrait',
    supportedModes: ['manual'],
    category: 'مستندات ملكية وهوية',
    subcategory: 'هويات',
    supportsGeneration: false,
    supportsCopy: true,
    supportsAI: false,
    readinessLevel: 'عالية',
    improvementStatus: 'مستقر',
    priority: 'عالية',
    usageCount: 15,
    lastUsedAt: '2026-04-04',
    officialCode: '136',
    officialCodeMode: 'numeric',
    officeCode: '1136',
    officeCodeMode: 'numeric',
    codeDisplayPriority: 'official',
    documentStyle: 'official-numbered-formal',
    mainCategory: 'مستندات ملكية وهوية',
    subCategory: 'هويات',
    mainCategoryCode: 'ID-01',
    subCategoryCode: 'ID-01-01',
    defaultBlocks: []
  },
  {
    id: 'survey-sketch',
    code: 'SK-001',
    internalCode: 'SKETCH-01',
    name: 'كروكي مساحي',
    description: 'كروكي الرفع المساحي',
    defaultSize: 'A3',
    defaultOrientation: 'landscape',
    supportedModes: ['manual', 'auto'],
    category: 'مستندات مساحية',
    subcategory: 'كروكيات',
    supportsGeneration: true,
    supportsCopy: true,
    supportsAI: false,
    readinessLevel: 'متوسطة',
    improvementStatus: 'تحت التطوير',
    priority: 'عالية',
    usageCount: 8,
    lastUsedAt: '2026-04-03',
    officialCode: '137',
    officialCodeMode: 'numeric',
    officeCode: '1137',
    officeCodeMode: 'numeric',
    codeDisplayPriority: 'official',
    documentStyle: 'official-numbered-formal',
    mainCategory: 'مستندات مساحية',
    subCategory: 'كروكيات',
    mainCategoryCode: 'SK-01',
    subCategoryCode: 'SK-01-01',
    defaultBlocks: []
  },
  {
    id: 'architectural-plan',
    code: 'AP-001',
    internalCode: 'ARCH-PLAN-01',
    name: 'مخطط معماري',
    description: 'المخططات المعمارية المعتمدة',
    defaultSize: 'A3',
    defaultOrientation: 'landscape',
    supportedModes: ['manual'],
    category: 'مستندات المخططات',
    subcategory: 'معمارية',
    supportsGeneration: false,
    supportsCopy: true,
    supportsAI: false,
    readinessLevel: 'متوسطة',
    improvementStatus: 'تحت التطوير',
    priority: 'عالية',
    usageCount: 4,
    lastUsedAt: '2026-04-01',
    officialCode: '138',
    officialCodeMode: 'numeric',
    officeCode: '1138',
    officeCodeMode: 'numeric',
    codeDisplayPriority: 'official',
    documentStyle: 'official-numbered-formal',
    mainCategory: 'مستندات المخططات',
    subCategory: 'معمارية',
    mainCategoryCode: 'ARCH-01',
    subCategoryCode: 'ARCH-01-01',
    defaultBlocks: []
  },
  {
    id: 'site-plan-dup',
    code: 'SP-001-DUP', // Adjusted duplicate code
    internalCode: 'SITE-PLAN-01',
    name: 'مخطط الموقع (مكرر)', // Added description to name
    description: 'مخطط الموقع العام',
    defaultSize: 'A3',
    defaultOrientation: 'landscape',
    supportedModes: ['manual', 'auto'],
    category: 'مستندات الموقع والخرائط',
    subcategory: 'مخططات',
    supportsGeneration: true,
    supportsCopy: true,
    supportsAI: false,
    readinessLevel: 'متوسطة',
    improvementStatus: 'تحت التطوير',
    priority: 'متوسطة',
    usageCount: 2,
    lastUsedAt: '2026-04-02',
    officialCode: '304',
    officialCodeMode: 'numeric',
    officeCode: '1304',
    officeCodeMode: 'numeric',
    codeDisplayPriority: 'official',
    documentStyle: 'official-numbered-formal',
    mainCategory: 'مستندات الموقع والخرائط',
    subCategory: 'مخططات',
    mainCategoryCode: 'SITE-01',
    subCategoryCode: 'SITE-01-01',
    defaultBlocks: []
  },
  {
    id: 'id-card-dup',
    code: 'ID-001-DUP', // Adjusted duplicate code
    internalCode: 'ID-CARD-01',
    name: 'الهوية الوطنية (مكرر)', // Added description to name
    description: 'صورة الهوية الوطنية',
    defaultSize: 'A4',
    defaultOrientation: 'portrait',
    supportedModes: ['manual'],
    category: 'مستندات ملكية وهوية',
    subcategory: 'هويات',
    supportsGeneration: false,
    supportsCopy: true,
    supportsAI: false,
    readinessLevel: 'عالية',
    improvementStatus: 'مستقر',
    priority: 'عالية',
    usageCount: 15,
    lastUsedAt: '2026-04-04',
    officialCode: '325',
    officialCodeMode: 'numeric',
    officeCode: '1325',
    officeCodeMode: 'numeric',
    codeDisplayPriority: 'official',
    documentStyle: 'official-numbered-formal',
    mainCategory: 'مستندات ملكية وهوية',
    subCategory: 'هويات',
    mainCategoryCode: 'PROP-01',
    subCategoryCode: 'PROP-01-01',
    defaultBlocks: []
  },
  {
    id: 'survey-sketch-dup',
    code: 'SK-001-DUP', // Adjusted duplicate code
    internalCode: 'SKETCH-01',
    name: 'كروكي مساحي (مكرر)', // Added description to name
    description: 'كروكي الرفع المساحي',
    defaultSize: 'A3',
    defaultOrientation: 'landscape',
    supportedModes: ['manual', 'auto'],
    category: 'مستندات مساحية',
    subcategory: 'كروكيات',
    supportsGeneration: true,
    supportsCopy: true,
    supportsAI: false,
    readinessLevel: 'متوسطة',
    improvementStatus: 'تحت التطوير',
    priority: 'عالية',
    usageCount: 8,
    lastUsedAt: '2026-04-03',
    officialCode: '346',
    officialCodeMode: 'numeric',
    officeCode: '1346',
    officeCodeMode: 'numeric',
    codeDisplayPriority: 'official',
    documentStyle: 'official-numbered-formal',
    mainCategory: 'مستندات مساحية',
    subCategory: 'كروكيات',
    mainCategoryCode: 'SURV-01',
    subCategoryCode: 'SURV-01-01',
    defaultBlocks: []
  },
  {
    id: 'architectural-plan-dup',
    code: 'AP-001-DUP', // Adjusted duplicate code
    internalCode: 'ARCH-PLAN-01',
    name: 'مخطط معماري (مكرر)', // Added description to name
    description: 'المخططات المعمارية المعتمدة',
    defaultSize: 'A3',
    defaultOrientation: 'landscape',
    supportedModes: ['manual'],
    category: 'مستندات المخططات',
    subcategory: 'معمارية',
    supportsGeneration: false,
    supportsCopy: true,
    supportsAI: false,
    readinessLevel: 'متوسطة',
    improvementStatus: 'تحت التطوير',
    priority: 'عالية',
    usageCount: 4,
    lastUsedAt: '2026-04-01',
    officialCode: '367',
    officialCodeMode: 'numeric',
    officeCode: '1367',
    officeCodeMode: 'numeric',
    codeDisplayPriority: 'official',
    documentStyle: 'official-numbered-formal',
    mainCategory: 'مستندات المخططات',
    subCategory: 'معمارية',
    mainCategoryCode: 'PLAN-01',
    subCategoryCode: 'PLAN-01-01',
    defaultBlocks: []
  },
  {
    id: 'energy-efficiency',
    code: 'EE-001',
    internalCode: 'ENERGY-01',
    name: 'شهادة كفاءة الطاقة',
    description: 'شهادة كفاءة الطاقة والعزل الحراري',
    defaultSize: 'A4',
    defaultOrientation: 'portrait',
    supportedModes: ['manual', 'auto'],
    category: 'مستندات شهادات واعتمادات',
    subcategory: 'شهادات',
    supportsGeneration: true,
    supportsCopy: true,
    supportsAI: false,
    readinessLevel: 'متوسطة',
    improvementStatus: 'تحت التطوير',
    priority: 'متوسطة',
    usageCount: 1,
    lastUsedAt: '2026-03-30',
    officialCode: '387',
    officialCodeMode: 'numeric',
    officeCode: '1387',
    officeCodeMode: 'numeric',
    codeDisplayPriority: 'official',
    documentStyle: 'official-numbered-formal',
    mainCategory: 'مستندات شهادات واعتمادات',
    subCategory: 'شهادات',
    mainCategoryCode: 'CERT-01',
    subCategoryCode: 'CERT-01-01',
    usageConstraints: {
      typeConditions: [],
      typePriority: 1,
      templateConditions: [],
      defaultTemplateId: 'default',
      forceManualReview: false,
      logicType: 'إلزامية'
    },
    defaultBlocks: []
  },
  { id: 'doc-001', legacyNo: '1', code: 'DOC-001', internalCode: 'INT-001', name: 'صورة بطاقة الاحوال المدنية للمالك / صورة جواز السفر لغير السعوديين', description: 'بطاقة الاحوال أو جواز السفر', defaultSize: 'A4', defaultOrientation: 'portrait', supportedModes: ['manual'], category: 'مستندات ملكية وهوية', subcategory: 'شخصية', supportsGeneration: false, supportsCopy: true, supportsAI: false, readinessLevel: 'عالية', improvementStatus: 'مستقر', priority: 'عالية', usageCount: 0, lastUsedAt: '2026-04-05', officialCode: '001', officialCodeMode: 'numeric', officeCode: '1001', officeCodeMode: 'numeric', codeDisplayPriority: 'official', documentStyle: 'official-numbered-formal', mainCategory: 'مستندات ملكية وهوية', subCategory: 'شخصية', mainCategoryCode: 'ID-01', subCategoryCode: 'ID-01-01', defaultBlocks: [] },
  { id: 'doc-002', legacyNo: '2', code: 'DOC-002', internalCode: 'INT-002', name: 'صك الملكية', description: 'صك الملكية', defaultSize: 'A4', defaultOrientation: 'portrait', supportedModes: ['manual'], category: 'مستندات ملكية وهوية', subcategory: 'عقارات', supportsGeneration: false, supportsCopy: true, supportsAI: false, readinessLevel: 'عالية', improvementStatus: 'مستقر', priority: 'عالية', usageCount: 0, lastUsedAt: '2026-04-05', officialCode: '002', officialCodeMode: 'numeric', officeCode: '1002', officeCodeMode: 'numeric', codeDisplayPriority: 'official', documentStyle: 'official-numbered-formal', mainCategory: 'مستندات ملكية وهوية', subCategory: 'عقارات', mainCategoryCode: 'PROP-01', subCategoryCode: 'PROP-01-01', defaultBlocks: [] },
  { id: 'doc-003', legacyNo: '3', code: 'DOC-003', internalCode: 'INT-003', name: 'الرفع المساحي موضحا المناسيب للشوارع المحيطة', description: 'رفع مساحي', defaultSize: 'A3', defaultOrientation: 'landscape', supportedModes: ['manual', 'auto', 'ai'], category: 'مستندات مساحية', subcategory: 'تقارير', supportsGeneration: true, supportsCopy: true, supportsAI: true, readinessLevel: 'عالية', improvementStatus: 'مستقر', priority: 'عالية', usageCount: 0, lastUsedAt: '2026-04-05', officialCode: '003', officialCodeMode: 'numeric', officeCode: '1003', officeCodeMode: 'numeric', codeDisplayPriority: 'official', documentStyle: 'official-numbered-formal', mainCategory: 'مستندات مساحية', subCategory: 'تقارير', mainCategoryCode: 'SURV-01', subCategoryCode: 'SURV-01-01', defaultBlocks: [] },
  { id: 'doc-004', legacyNo: '4', code: 'DOC-004', internalCode: 'INT-004', name: 'كروكي الموقع (صورة جزئية من خريطة الموقع)', description: 'كروكي الموقع', defaultSize: 'A3', defaultOrientation: 'landscape', supportedModes: ['manual', 'auto'], category: 'مستندات مساحية', subcategory: 'خرائط', supportsGeneration: true, supportsCopy: true, supportsAI: false, readinessLevel: 'عالية', improvementStatus: 'مستقر', priority: 'عالية', usageCount: 0, lastUsedAt: '2026-04-05', officialCode: '004', officialCodeMode: 'numeric', officeCode: '1004', officeCodeMode: 'numeric', codeDisplayPriority: 'official', documentStyle: 'official-numbered-formal', mainCategory: 'مستندات مساحية', subCategory: 'خرائط', mainCategoryCode: 'SURV-01', subCategoryCode: 'SURV-01-02', defaultBlocks: [] },
  { id: 'doc-005', legacyNo: '5', code: 'DOC-005', internalCode: 'INT-005', name: 'مسودة رخصة بناء يتم اعدادها من المكتب الهندسي', description: 'مسودة رخصة', defaultSize: 'A4', defaultOrientation: 'portrait', supportedModes: ['manual', 'auto', 'ai'], category: 'مستندات إدارية ومساندة', subcategory: 'بناء', supportsGeneration: true, supportsCopy: true, supportsAI: true, readinessLevel: 'متوسطة', improvementStatus: 'تحت التطوير', priority: 'عالية', usageCount: 0, lastUsedAt: '2026-04-05', officialCode: '005', officialCodeMode: 'numeric', officeCode: '1005', officeCodeMode: 'numeric', codeDisplayPriority: 'official', documentStyle: 'official-numbered-formal', mainCategory: 'مستندات إدارية ومساندة', subCategory: 'بناء', mainCategoryCode: 'ADM-01', subCategoryCode: 'ADM-01-01', defaultBlocks: [] },
  { id: 'doc-006', legacyNo: '6', code: 'DOC-006', internalCode: 'INT-006', name: 'نموذج توثيق رقم المشروع الخاص', description: 'نموذج توثيق', defaultSize: 'A4', defaultOrientation: 'portrait', supportedModes: ['manual', 'auto'], category: 'مستندات إدارية ومساندة', subcategory: 'نماذج', supportsGeneration: true, supportsCopy: true, supportsAI: false, readinessLevel: 'عالية', improvementStatus: 'مستقر', priority: 'عالية', usageCount: 0, lastUsedAt: '2026-04-05', officialCode: '006', officialCodeMode: 'numeric', officeCode: '1006', officeCodeMode: 'numeric', codeDisplayPriority: 'official', documentStyle: 'official-numbered-formal', mainCategory: 'مستندات إدارية ومساندة', subCategory: 'نماذج', mainCategoryCode: 'ADM-01', subCategoryCode: 'ADM-01-02', defaultBlocks: [] },
  { id: 'doc-007', legacyNo: '7', code: 'DOC-007', internalCode: 'INT-007', name: 'اقرار من المكتب الهندسي لتحمل مسؤولية الدراسة المعمارية والانشائية والكهربائية والميكانيكية بموجب اتفاقية بين المالك والمكتب الهندسي المصمم والامانة', description: 'إقرار مسؤولية', defaultSize: 'A4', defaultOrientation: 'portrait', supportedModes: ['manual', 'auto'], category: 'مستندات نماذج وتعهدات', subcategory: 'هندسي', supportsGeneration: true, supportsCopy: true, supportsAI: false, readinessLevel: 'عالية', improvementStatus: 'مستقر', priority: 'عالية', usageCount: 0, lastUsedAt: '2026-04-05', officialCode: '007', officialCodeMode: 'numeric', officeCode: '1007', officeCodeMode: 'numeric', codeDisplayPriority: 'official', documentStyle: 'official-numbered-formal', mainCategory: 'مستندات نماذج وتعهدات', subCategory: 'هندسي', mainCategoryCode: 'FORM-01', subCategoryCode: 'FORM-01-01', defaultBlocks: [] },
  { id: 'doc-008', legacyNo: '8', code: 'DOC-008', internalCode: 'INT-008', name: 'ايصال سداد الرسوم', description: 'إيصال سداد', defaultSize: 'A4', defaultOrientation: 'portrait', supportedModes: ['manual'], category: 'مستندات تصفيات وخدمات', subcategory: 'إيصالات', supportsGeneration: false, supportsCopy: true, supportsAI: false, readinessLevel: 'عالية', improvementStatus: 'مستقر', priority: 'عالية', usageCount: 0, lastUsedAt: '2026-04-05', officialCode: '008', officialCodeMode: 'numeric', officeCode: '1008', officeCodeMode: 'numeric', codeDisplayPriority: 'official', documentStyle: 'official-numbered-formal', mainCategory: 'مستندات تصفيات وخدمات', subCategory: 'إيصالات', mainCategoryCode: 'SVC-01', subCategoryCode: 'SVC-01-01', defaultBlocks: [] },
  { id: 'doc-009', legacyNo: '9', code: 'DOC-009', internalCode: 'INT-009', name: 'نموذج تدقيق نظام واشتراطات البناء', description: 'نموذج تدقيق', defaultSize: 'A4', defaultOrientation: 'portrait', supportedModes: ['manual', 'auto', 'ai'], category: 'مستندات إدارية ومساندة', subcategory: 'نماذج', supportsGeneration: true, supportsCopy: true, supportsAI: true, readinessLevel: 'عالية', improvementStatus: 'مستقر', priority: 'عالية', usageCount: 0, lastUsedAt: '2026-04-05', officialCode: '009', officialCodeMode: 'numeric', officeCode: '1009', officeCodeMode: 'numeric', codeDisplayPriority: 'official', documentStyle: 'official-numbered-formal', mainCategory: 'مستندات إدارية ومساندة', subCategory: 'نماذج', mainCategoryCode: 'ADM-01', subCategoryCode: 'ADM-01-03', defaultBlocks: [] },
  { id: 'doc-010', legacyNo: '10', code: 'DOC-010', internalCode: 'INT-010', name: 'المخططات النهائية للمشروع', description: 'مخططات نهائية', defaultSize: 'A3', defaultOrientation: 'landscape', supportedModes: ['manual', 'auto', 'ai'], category: 'مستندات المخططات', subcategory: 'نهائية', supportsGeneration: true, supportsCopy: true, supportsAI: true, readinessLevel: 'عالية', improvementStatus: 'مستقر', priority: 'عالية', usageCount: 0, lastUsedAt: '2026-04-05', officialCode: '010', officialCodeMode: 'numeric', officeCode: '1010', officeCodeMode: 'numeric', codeDisplayPriority: 'official', documentStyle: 'official-numbered-formal', mainCategory: 'مستندات المخططات', subCategory: 'نهائية', mainCategoryCode: 'PLAN-01', subCategoryCode: 'PLAN-01-01', defaultBlocks: [] },
  { id: 'doc-011', legacyNo: '11', code: 'DOC-011', internalCode: 'INT-011', name: 'نموذج بيانات ومرفقات المشروع', description: 'نموذج بيانات', defaultSize: 'A4', defaultOrientation: 'portrait', supportedModes: ['manual', 'auto'], category: 'مستندات إدارية ومساندة', subcategory: 'نماذج', supportsGeneration: true, supportsCopy: true, supportsAI: false, readinessLevel: 'عالية', improvementStatus: 'مستقر', priority: 'عالية', usageCount: 0, lastUsedAt: '2026-04-05', officialCode: '011', officialCodeMode: 'numeric', officeCode: '1011', officeCodeMode: 'numeric', codeDisplayPriority: 'official', documentStyle: 'official-numbered-formal', mainCategory: 'مستندات إدارية ومساندة', subCategory: 'نماذج', mainCategoryCode: 'ADM-01', subCategoryCode: 'ADM-01-04', defaultBlocks: [] },
  { id: 'doc-012', legacyNo: '12', code: 'DOC-012', internalCode: 'INT-012', name: 'الموقع العام موضحا عليه المبنى المراد بناؤه', description: 'موقع عام', defaultSize: 'A3', defaultOrientation: 'landscape', supportedModes: ['manual', 'auto', 'ai'], category: 'مستندات المخططات', subcategory: 'موقع عام', supportsGeneration: true, supportsCopy: true, supportsAI: true, readinessLevel: 'عالية', improvementStatus: 'مستقر', priority: 'عالية', usageCount: 0, lastUsedAt: '2026-04-05', officialCode: '012', officialCodeMode: 'numeric', officeCode: '1012', officeCodeMode: 'numeric', codeDisplayPriority: 'official', documentStyle: 'official-numbered-formal', mainCategory: 'مستندات المخططات', subCategory: 'موقع عام', mainCategoryCode: 'PLAN-01', subCategoryCode: 'PLAN-01-02', defaultBlocks: [] },
  { id: 'doc-013', legacyNo: '13', code: 'DOC-013', internalCode: 'INT-013', name: 'الموقع العام موضحا عليه جميع الأعمال', description: 'موقع عام', defaultSize: 'A3', defaultOrientation: 'landscape', supportedModes: ['manual', 'auto', 'ai'], category: 'مستندات المخططات', subcategory: 'موقع عام', supportsGeneration: true, supportsCopy: true, supportsAI: true, readinessLevel: 'عالية', improvementStatus: 'مستقر', priority: 'عالية', usageCount: 0, lastUsedAt: '2026-04-05', officialCode: '013', officialCodeMode: 'numeric', officeCode: '1013', officeCodeMode: 'numeric', codeDisplayPriority: 'official', documentStyle: 'official-numbered-formal', mainCategory: 'مستندات المخططات', subCategory: 'موقع عام', mainCategoryCode: 'PLAN-01', subCategoryCode: 'PLAN-01-03', defaultBlocks: [] },
  { id: 'doc-014', legacyNo: '14', code: 'DOC-014', internalCode: 'INT-014', name: 'الموقع العام موضحا عليه جدول المساحات ونسب البناء والشوارع المحيطة ومقياس الرسم', description: 'موقع عام', defaultSize: 'A3', defaultOrientation: 'landscape', supportedModes: ['manual', 'auto', 'ai'], category: 'مستندات المخططات', subcategory: 'موقع عام', supportsGeneration: true, supportsCopy: true, supportsAI: true, readinessLevel: 'عالية', improvementStatus: 'مستقر', priority: 'عالية', usageCount: 0, lastUsedAt: '2026-04-05', officialCode: '014', officialCodeMode: 'numeric', officeCode: '1014', officeCodeMode: 'numeric', codeDisplayPriority: 'official', documentStyle: 'official-numbered-formal', mainCategory: 'مستندات المخططات', subCategory: 'موقع عام', mainCategoryCode: 'PLAN-01', subCategoryCode: 'PLAN-01-04', defaultBlocks: [] },
  { id: 'doc-015', legacyNo: '15', code: 'DOC-015', internalCode: 'INT-015', name: 'شهادة الإشغال', description: 'شهادة إشغال', defaultSize: 'A4', defaultOrientation: 'portrait', supportedModes: ['manual'], category: 'مستندات شهادات واعتمادات', subcategory: 'إشغال', supportsGeneration: true, supportsCopy: true, supportsAI: false, readinessLevel: 'عالية', improvementStatus: 'مستقر', priority: 'عالية', usageCount: 0, lastUsedAt: '2026-04-05', officialCode: '015', officialCodeMode: 'numeric', officeCode: '1015', officeCodeMode: 'numeric', codeDisplayPriority: 'official', documentStyle: 'official-numbered-formal', mainCategory: 'مستندات شهادات واعتمادات', subCategory: 'إشغال', mainCategoryCode: 'CERT-01', subCategoryCode: 'CERT-01-01', defaultBlocks: [] },
  { id: 'doc-016', legacyNo: '16', code: 'DOC-016', internalCode: 'INT-016', name: 'صورة جزئية لموقع البناء من خريطة القطعة', description: 'صورة جزئية', defaultSize: 'A4', defaultOrientation: 'portrait', supportedModes: ['manual'], category: 'مستندات مساحية', subcategory: 'خرائط', supportsGeneration: false, supportsCopy: true, supportsAI: false, readinessLevel: 'عالية', improvementStatus: 'مستقر', priority: 'عالية', usageCount: 0, lastUsedAt: '2026-04-05', officialCode: '016', officialCodeMode: 'numeric', officeCode: '1016', officeCodeMode: 'numeric', codeDisplayPriority: 'official', documentStyle: 'official-numbered-formal', mainCategory: 'مستندات مساحية', subCategory: 'خرائط', mainCategoryCode: 'SURV-01', subCategoryCode: 'SURV-01-05', defaultBlocks: [] },
  { id: 'doc-017', legacyNo: '17', code: 'DOC-017', internalCode: 'INT-017', name: 'صورة اجابة سريعة بها تحديد الموقع', description: 'صورة إجابة', defaultSize: 'A4', defaultOrientation: 'portrait', supportedModes: ['manual'], category: 'مستندات مساحية', subcategory: 'خرائط', supportsGeneration: false, supportsCopy: true, supportsAI: false, readinessLevel: 'عالية', improvementStatus: 'مستقر', priority: 'عالية', usageCount: 0, lastUsedAt: '2026-04-05', officialCode: '017', officialCodeMode: 'numeric', officeCode: '1017', officeCodeMode: 'numeric', codeDisplayPriority: 'official', documentStyle: 'official-numbered-formal', mainCategory: 'مستندات مساحية', subCategory: 'خرائط', mainCategoryCode: 'SURV-01', subCategoryCode: 'SURV-01-06', defaultBlocks: [] },
  { id: 'doc-019', legacyNo: '19', code: 'DOC-019', internalCode: 'INT-019', name: 'صورة فاتورة حاوية', description: 'فاتورة حاوية', defaultSize: 'A4', defaultOrientation: 'portrait', supportedModes: ['manual'], category: 'مستندات تصفيات وخدمات', subcategory: 'فواتير', supportsGeneration: false, supportsCopy: true, supportsAI: false, readinessLevel: 'عالية', improvementStatus: 'مستقر', priority: 'عالية', usageCount: 0, lastUsedAt: '2026-04-05', officialCode: '019', officialCodeMode: 'numeric', officeCode: '1019', officeCodeMode: 'numeric', codeDisplayPriority: 'official', documentStyle: 'official-numbered-formal', mainCategory: 'مستندات تصفيات وخدمات', subCategory: 'فواتير', mainCategoryCode: 'SVC-01', subCategoryCode: 'SVC-01-02', defaultBlocks: [] },
  { id: 'doc-021', legacyNo: '21', code: 'DOC-021', internalCode: 'INT-021', name: 'إقرار المالك بتنفيذ لائحة الضوابط والشروط', description: 'إقرار مالك', defaultSize: 'A4', defaultOrientation: 'portrait', supportedModes: ['manual', 'auto'], category: 'مستندات نماذج وتعهدات', subcategory: 'مالك', supportsGeneration: true, supportsCopy: true, supportsAI: false, readinessLevel: 'عالية', improvementStatus: 'مستقر', priority: 'عالية', usageCount: 0, lastUsedAt: '2026-04-05', officialCode: '021', officialCodeMode: 'numeric', officeCode: '1021', officeCodeMode: 'numeric', codeDisplayPriority: 'official', documentStyle: 'official-numbered-formal', mainCategory: 'مستندات نماذج وتعهدات', subCategory: 'مالك', mainCategoryCode: 'FORM-01', subCategoryCode: 'FORM-01-02', defaultBlocks: [] },
  { id: 'doc-022', legacyNo: '22', code: 'DOC-022', internalCode: 'INT-022', name: 'إقرار المالك والمكتب الهندسي المشرف', description: 'إقرار مشترك', defaultSize: 'A4', defaultOrientation: 'portrait', supportedModes: ['manual', 'auto'], category: 'مستندات نماذج وتعهدات', subcategory: 'مشترك', supportsGeneration: true, supportsCopy: true, supportsAI: false, readinessLevel: 'عالية', improvementStatus: 'مستقر', priority: 'عالية', usageCount: 0, lastUsedAt: '2026-04-05', officialCode: '022', officialCodeMode: 'numeric', officeCode: '1022', officeCodeMode: 'numeric', codeDisplayPriority: 'official', documentStyle: 'official-numbered-formal', mainCategory: 'مستندات نماذج وتعهدات', subCategory: 'مشترك', mainCategoryCode: 'FORM-01', subCategoryCode: 'FORM-01-03', defaultBlocks: [] },
  { id: 'doc-023', legacyNo: '23', code: 'DOC-023', internalCode: 'INT-023', name: 'تقرير مساحي من مكتب مساحة معتمد', description: 'تقرير مساحي', defaultSize: 'A3', defaultOrientation: 'landscape', supportedModes: ['manual', 'auto', 'ai'], category: 'مساحة', subcategory: 'تقارير', supportsGeneration: true, supportsCopy: true, supportsAI: true, readinessLevel: 'عالية', improvementStatus: 'مستقر', priority: 'عالية', usageCount: 0, lastUsedAt: '2026-04-05', officialCode: '023', officialCodeMode: 'numeric', officeCode: '1023', officeCodeMode: 'numeric', codeDisplayPriority: 'official', documentStyle: 'official-numbered-formal', mainCategory: 'مستندات مساحية', subCategory: 'تقارير', mainCategoryCode: 'SURV-01', subCategoryCode: 'SURV-01-07', defaultBlocks: [] },
  { id: 'doc-024', legacyNo: '24', code: 'DOC-024', internalCode: 'INT-024', name: 'صورة رخصة البناء', description: 'رخصة بناء', defaultSize: 'A4', defaultOrientation: 'portrait', supportedModes: ['manual'], category: 'رخص', subcategory: 'بناء', supportsGeneration: false, supportsCopy: true, supportsAI: false, readinessLevel: 'عالية', improvementStatus: 'مستقر', priority: 'عالية', usageCount: 0, lastUsedAt: '2026-04-05', officialCode: '024', officialCodeMode: 'numeric', officeCode: '1024', officeCodeMode: 'numeric', codeDisplayPriority: 'official', documentStyle: 'official-numbered-formal', mainCategory: 'رخص', subCategory: 'بناء', mainCategoryCode: 'LIC-01', subCategoryCode: 'LIC-01-01', defaultBlocks: [] },
  { id: 'doc-025', legacyNo: '25', code: 'DOC-025', internalCode: 'INT-025', name: 'منسوب الشارع في حالة كان الشارع غير منفذ', description: 'منسوب شارع', defaultSize: 'A4', defaultOrientation: 'portrait', supportedModes: ['manual', 'auto'], category: 'مساحة', subcategory: 'تقارير', supportsGeneration: true, supportsCopy: true, supportsAI: false, readinessLevel: 'متوسطة', improvementStatus: 'تحت التطوير', priority: 'عالية', usageCount: 0, lastUsedAt: '2026-04-05', officialCode: '025', officialCodeMode: 'numeric', officeCode: '1025', officeCodeMode: 'numeric', codeDisplayPriority: 'official', documentStyle: 'official-numbered-formal', mainCategory: 'مستندات مساحية', subCategory: 'تقارير', mainCategoryCode: 'SURV-01', subCategoryCode: 'SURV-01-08', defaultBlocks: [] },
  { id: 'doc-026', legacyNo: '26', code: 'DOC-026', internalCode: 'INT-026', name: 'محضر تجزئة', description: 'محضر تجزئة', defaultSize: 'A4', defaultOrientation: 'portrait', supportedModes: ['manual', 'auto'], category: 'تجزئة', subcategory: 'محاضر', supportsGeneration: true, supportsCopy: true, supportsAI: false, readinessLevel: 'عالية', improvementStatus: 'مستقر', priority: 'عالية', usageCount: 0, lastUsedAt: '2026-04-05', officialCode: '026', officialCodeMode: 'numeric', officeCode: '1026', officeCodeMode: 'numeric', codeDisplayPriority: 'official', documentStyle: 'official-numbered-formal', mainCategory: 'مستندات مساحية', subCategory: 'تجزئة', mainCategoryCode: 'SURV-01', subCategoryCode: 'SURV-01-09', defaultBlocks: [] },
  { id: 'doc-027', legacyNo: '27', code: 'DOC-027', internalCode: 'INT-027', name: 'تصفية خدمات (شركة الكهرباء)', description: 'تصفية كهرباء', defaultSize: 'A4', defaultOrientation: 'portrait', supportedModes: ['manual', 'auto'], category: 'خدمات', subcategory: 'تصفية', supportsGeneration: true, supportsCopy: true, supportsAI: false, readinessLevel: 'عالية', improvementStatus: 'مستقر', priority: 'عالية', usageCount: 0, lastUsedAt: '2026-04-05', officialCode: '027', officialCodeMode: 'numeric', officeCode: '1027', officeCodeMode: 'numeric', codeDisplayPriority: 'official', documentStyle: 'official-numbered-formal', mainCategory: 'مستندات تصفيات وخدمات', subCategory: 'كهرباء', mainCategoryCode: 'SVC-01', subCategoryCode: 'SVC-01-03', defaultBlocks: [] },
  { id: 'doc-028', legacyNo: '28', code: 'DOC-028', internalCode: 'INT-028', name: 'تصفية خدمات (شركة المياة الوطنية)', description: 'تصفية مياه', defaultSize: 'A4', defaultOrientation: 'portrait', supportedModes: ['manual', 'auto'], category: 'خدمات', subcategory: 'تصفية', supportsGeneration: true, supportsCopy: true, supportsAI: false, readinessLevel: 'عالية', improvementStatus: 'مستقر', priority: 'عالية', usageCount: 0, lastUsedAt: '2026-04-05', officialCode: '028', officialCodeMode: 'numeric', officeCode: '1028', officeCodeMode: 'numeric', codeDisplayPriority: 'official', documentStyle: 'official-numbered-formal', mainCategory: 'مستندات تصفيات وخدمات', subCategory: 'مياه', mainCategoryCode: 'SVC-01', subCategoryCode: 'SVC-01-04', defaultBlocks: [] },
  { id: 'doc-029', legacyNo: '29', code: 'DOC-029', internalCode: 'INT-029', name: 'تصفية خدمات (شركة الإتصالات)', description: 'تصفية اتصالات', defaultSize: 'A4', defaultOrientation: 'portrait', supportedModes: ['manual', 'auto'], category: 'خدمات', subcategory: 'تصفية', supportsGeneration: true, supportsCopy: true, supportsAI: false, readinessLevel: 'عالية', improvementStatus: 'مستقر', priority: 'عالية', usageCount: 0, lastUsedAt: '2026-04-05', officialCode: '029', officialCodeMode: 'numeric', officeCode: '1029', officeCodeMode: 'numeric', codeDisplayPriority: 'official', documentStyle: 'official-numbered-formal', mainCategory: 'مستندات تصفيات وخدمات', subCategory: 'اتصالات', mainCategoryCode: 'SVC-01', subCategoryCode: 'SVC-01-05', defaultBlocks: [] },
  { id: 'doc-030', legacyNo: '30', code: 'DOC-030', internalCode: 'INT-030', name: 'شهادة تحمل المبنى (مكتب هندسي)', description: 'شهادة تحمل', defaultSize: 'A4', defaultOrientation: 'portrait', supportedModes: ['manual', 'auto'], category: 'مستندات شهادات واعتمادات', subcategory: 'هندسي', supportsGeneration: true, supportsCopy: true, supportsAI: false, readinessLevel: 'عالية', improvementStatus: 'مستقر', priority: 'عالية', usageCount: 0, lastUsedAt: '2026-04-05', officialCode: '030', officialCodeMode: 'numeric', officeCode: '1030', officeCodeMode: 'numeric', codeDisplayPriority: 'official', documentStyle: 'official-numbered-formal', mainCategory: 'مستندات شهادات واعتمادات', subCategory: 'هندسي', mainCategoryCode: 'CERT-01', subCategoryCode: 'CERT-01-02', defaultBlocks: [] },
  { id: 'doc-031', legacyNo: '31', code: 'DOC-031', internalCode: 'INT-031', name: 'صورة الوكالة الشرعية في حالة مقدم الطلب وكيل', description: 'وكالة شرعية', defaultSize: 'A4', defaultOrientation: 'portrait', supportedModes: ['manual'], category: 'مستندات قانونية وتفويضات', subcategory: 'شخصية', supportsGeneration: false, supportsCopy: true, supportsAI: false, readinessLevel: 'عالية', improvementStatus: 'مستقر', priority: 'عالية', usageCount: 0, lastUsedAt: '2026-04-05', officialCode: '031', officialCodeMode: 'numeric', officeCode: '1031', officeCodeMode: 'numeric', codeDisplayPriority: 'official', documentStyle: 'official-numbered-formal', mainCategory: 'مستندات قانونية وتفويضات', subCategory: 'شخصية', mainCategoryCode: 'LEG-01', subCategoryCode: 'LEG-01-01', defaultBlocks: [] },
  { id: 'doc-032', legacyNo: '32', code: 'DOC-032', internalCode: 'INT-032', name: 'تفويض مصدق من الغرفة التجارية', description: 'تفويض', defaultSize: 'A4', defaultOrientation: 'portrait', supportedModes: ['manual'], category: 'مستندات قانونية وتفويضات', subcategory: 'إداري', supportsGeneration: false, supportsCopy: true, supportsAI: false, readinessLevel: 'عالية', improvementStatus: 'مستقر', priority: 'عالية', usageCount: 0, lastUsedAt: '2026-04-05', officialCode: '032', officialCodeMode: 'numeric', officeCode: '1032', officeCodeMode: 'numeric', codeDisplayPriority: 'official', documentStyle: 'official-numbered-formal', mainCategory: 'مستندات قانونية وتفويضات', subCategory: 'إداري', mainCategoryCode: 'LEG-01', subCategoryCode: 'LEG-01-02', defaultBlocks: [] },
  { id: 'doc-033', legacyNo: '33', code: 'DOC-033', internalCode: 'INT-033', name: 'كروكي تجزئة بالاطوال والمساحات', description: 'كروكي تجزئة', defaultSize: 'A3', defaultOrientation: 'landscape', supportedModes: ['manual', 'auto'], category: 'مستندات مساحية', subcategory: 'كروكيات', supportsGeneration: true, supportsCopy: true, supportsAI: false, readinessLevel: 'عالية', improvementStatus: 'مستقر', priority: 'عالية', usageCount: 0, lastUsedAt: '2026-04-05', officialCode: '033', officialCodeMode: 'numeric', officeCode: '1033', officeCodeMode: 'numeric', codeDisplayPriority: 'official', documentStyle: 'official-numbered-formal', mainCategory: 'مستندات مساحية', subCategory: 'كروكيات', mainCategoryCode: 'SURV-01', subCategoryCode: 'SURV-01-10', defaultBlocks: [] },
  { id: 'doc-034', legacyNo: '34', code: 'DOC-034', internalCode: 'INT-034', name: 'صورة الواجهة', description: 'صورة واجهة', defaultSize: 'A4', defaultOrientation: 'portrait', supportedModes: ['manual'], category: 'مستندات فنية', subcategory: 'واجهات', supportsGeneration: false, supportsCopy: true, supportsAI: false, readinessLevel: 'عالية', improvementStatus: 'مستقر', priority: 'عالية', usageCount: 0, lastUsedAt: '2026-04-05', officialCode: '034', officialCodeMode: 'numeric', officeCode: '1034', officeCodeMode: 'numeric', codeDisplayPriority: 'official', documentStyle: 'official-numbered-formal', mainCategory: 'مستندات فنية', subCategory: 'واجهات', mainCategoryCode: 'TECH-01', subCategoryCode: 'TECH-01-01', defaultBlocks: [] },
  { id: 'doc-035', legacyNo: '35', code: 'DOC-035', internalCode: 'INT-035', name: 'تعهد العزل الحراري', description: 'تعهد عزل', defaultSize: 'A4', defaultOrientation: 'portrait', supportedModes: ['manual', 'auto'], category: 'مستندات نماذج وتعهدات', subcategory: 'هندسي', supportsGeneration: true, supportsCopy: true, supportsAI: false, readinessLevel: 'عالية', improvementStatus: 'مستقر', priority: 'عالية', usageCount: 0, lastUsedAt: '2026-04-05', officialCode: '035', officialCodeMode: 'numeric', officeCode: '1035', officeCodeMode: 'numeric', codeDisplayPriority: 'official', documentStyle: 'official-numbered-formal', mainCategory: 'مستندات نماذج وتعهدات', subCategory: 'هندسي', mainCategoryCode: 'FORM-01', subCategoryCode: 'FORM-01-04', defaultBlocks: [] },
  { id: 'doc-036', legacyNo: '36', code: 'DOC-036', internalCode: 'INT-036', name: 'الهيئة السعودية للمهندسين', description: 'هيئة المهندسين', defaultSize: 'A4', defaultOrientation: 'portrait', supportedModes: ['manual'], category: 'مستندات إدارية ومساندة', subcategory: 'اعتماد', supportsGeneration: false, supportsCopy: true, supportsAI: false, readinessLevel: 'عالية', improvementStatus: 'مستقر', priority: 'عالية', usageCount: 0, lastUsedAt: '2026-04-05', officialCode: '036', officialCodeMode: 'numeric', officeCode: '1036', officeCodeMode: 'numeric', codeDisplayPriority: 'official', documentStyle: 'official-numbered-formal', mainCategory: 'مستندات إدارية ومساندة', subCategory: 'اعتماد', mainCategoryCode: 'ADMIN-01', subCategoryCode: 'ADMIN-01-01', defaultBlocks: [] },
  { id: 'doc-037', legacyNo: '37', code: 'DOC-037', internalCode: 'INT-037', name: 'سجل تجاري', description: 'سجل تجاري', defaultSize: 'A4', defaultOrientation: 'portrait', supportedModes: ['manual'], category: 'مستندات إدارية ومساندة', subcategory: 'شركات', supportsGeneration: false, supportsCopy: true, supportsAI: false, readinessLevel: 'عالية', improvementStatus: 'مستقر', priority: 'عالية', usageCount: 0, lastUsedAt: '2026-04-05', officialCode: '037', officialCodeMode: 'numeric', officeCode: '1037', officeCodeMode: 'numeric', codeDisplayPriority: 'official', documentStyle: 'official-numbered-formal', mainCategory: 'مستندات إدارية ومساندة', subCategory: 'شركات', mainCategoryCode: 'ADMIN-01', subCategoryCode: 'ADMIN-01-02', defaultBlocks: [] },
  { id: 'doc-038', legacyNo: '38', code: 'DOC-038', internalCode: 'INT-038', name: 'التأمينات والسعودة', description: 'تأمينات وسعودة', defaultSize: 'A4', defaultOrientation: 'portrait', supportedModes: ['manual'], category: 'مستندات إدارية ومساندة', subcategory: 'موظفين', supportsGeneration: false, supportsCopy: true, supportsAI: false, readinessLevel: 'عالية', improvementStatus: 'مستقر', priority: 'عالية', usageCount: 0, lastUsedAt: '2026-04-05', officialCode: '038', officialCodeMode: 'numeric', officeCode: '1038', officeCodeMode: 'numeric', codeDisplayPriority: 'official', documentStyle: 'official-numbered-formal', mainCategory: 'مستندات إدارية ومساندة', subCategory: 'موظفين', mainCategoryCode: 'ADMIN-01', subCategoryCode: 'ADMIN-01-03', defaultBlocks: [] },
  { id: 'doc-039', legacyNo: '39', code: 'DOC-039', internalCode: 'INT-039', name: 'السيرة الذاتية للعاملين بالمكتب', description: 'سيرة ذاتية', defaultSize: 'A4', defaultOrientation: 'portrait', supportedModes: ['manual'], category: 'مستندات إدارية ومساندة', subcategory: 'موظفين', supportsGeneration: false, supportsCopy: true, supportsAI: false, readinessLevel: 'عالية', improvementStatus: 'مستقر', priority: 'عالية', usageCount: 0, lastUsedAt: '2026-04-05', officialCode: '039', officialCodeMode: 'numeric', officeCode: '1039', officeCodeMode: 'numeric', codeDisplayPriority: 'official', documentStyle: 'official-numbered-formal', mainCategory: 'مستندات إدارية ومساندة', subCategory: 'موظفين', mainCategoryCode: 'ADMIN-01', subCategoryCode: 'ADMIN-01-04', defaultBlocks: [] },
  { id: 'doc-040', legacyNo: '40', code: 'DOC-040', internalCode: 'INT-040', name: 'رخصة محل', description: 'رخصة محل', defaultSize: 'A4', defaultOrientation: 'portrait', supportedModes: ['manual'], category: 'مستندات إدارية ومساندة', subcategory: 'إداري', supportsGeneration: false, supportsCopy: true, supportsAI: false, readinessLevel: 'عالية', improvementStatus: 'مستقر', priority: 'عالية', usageCount: 0, lastUsedAt: '2026-04-05', officialCode: '040', officialCodeMode: 'numeric', officeCode: '1040', officeCodeMode: 'numeric', codeDisplayPriority: 'official', documentStyle: 'official-numbered-formal', mainCategory: 'مستندات إدارية ومساندة', subCategory: 'إداري', mainCategoryCode: 'ADMIN-01', subCategoryCode: 'ADMIN-01-05', defaultBlocks: [] },
  { id: 'doc-041', legacyNo: '41', code: 'DOC-041', internalCode: 'INT-041', name: 'صورة المؤهل', description: 'صورة مؤهل', defaultSize: 'A4', defaultOrientation: 'portrait', supportedModes: ['manual'], category: 'مستندات إدارية ومساندة', subcategory: 'موظفين', supportsGeneration: false, supportsCopy: true, supportsAI: false, readinessLevel: 'عالية', improvementStatus: 'مستقر', priority: 'عالية', usageCount: 0, lastUsedAt: '2026-04-05', officialCode: '041', officialCodeMode: 'numeric', officeCode: '1041', officeCodeMode: 'numeric', codeDisplayPriority: 'official', documentStyle: 'official-numbered-formal', mainCategory: 'مستندات إدارية ومساندة', subCategory: 'موظفين', mainCategoryCode: 'ADMIN-01', subCategoryCode: 'ADMIN-01-06', defaultBlocks: [] },
  { id: 'doc-042', legacyNo: '42', code: 'DOC-042', internalCode: 'INT-042', name: 'استيكر مكتب هندسي', description: 'استيكر مكتب', defaultSize: 'A4', defaultOrientation: 'portrait', supportedModes: ['manual'], category: 'مستندات إدارية ومساندة', subcategory: 'اعتماد', supportsGeneration: false, supportsCopy: true, supportsAI: false, readinessLevel: 'عالية', improvementStatus: 'مستقر', priority: 'عالية', usageCount: 0, lastUsedAt: '2026-04-05', officialCode: '042', officialCodeMode: 'numeric', officeCode: '1042', officeCodeMode: 'numeric', codeDisplayPriority: 'official', documentStyle: 'official-numbered-formal', mainCategory: 'مستندات إدارية ومساندة', subCategory: 'اعتماد', mainCategoryCode: 'ADMIN-01', subCategoryCode: 'ADMIN-01-07', defaultBlocks: [] },
  { id: 'doc-098', legacyNo: '98', code: 'DOC-098', internalCode: 'INT-098', name: 'وثيقة التأمين ضد العيوب الخفية', description: 'تأمين عيوب خفية', defaultSize: 'A4', defaultOrientation: 'portrait', supportedModes: ['manual', 'auto'], category: 'مستندات قانونية وتفويضات', subcategory: 'قانوني', supportsGeneration: true, supportsCopy: true, supportsAI: false, readinessLevel: 'عالية', improvementStatus: 'مستقر', priority: 'عالية', usageCount: 0, lastUsedAt: '2026-04-05', officialCode: '098', officialCodeMode: 'numeric', officeCode: '1098', officeCodeMode: 'numeric', codeDisplayPriority: 'official', documentStyle: 'official-numbered-formal', mainCategory: 'مستندات قانونية وتفويضات', subCategory: 'قانوني', mainCategoryCode: 'LEG-01', subCategoryCode: 'LEG-01-03', defaultBlocks: [] },
  { id: 'doc-099', legacyNo: '99', code: 'DOC-099', internalCode: 'INT-099', name: 'عقد تفويض المالك لمكتب هندسي', description: 'عقد تفويض', defaultSize: 'A4', defaultOrientation: 'portrait', supportedModes: ['manual', 'auto'], category: 'مستندات قانونية وتفويضات', subcategory: 'مالك', supportsGeneration: true, supportsCopy: true, supportsAI: false, readinessLevel: 'عالية', improvementStatus: 'مستقر', priority: 'عالية', usageCount: 0, lastUsedAt: '2026-04-05', officialCode: '099', officialCodeMode: 'numeric', officeCode: '1099', officeCodeMode: 'numeric', codeDisplayPriority: 'official', documentStyle: 'official-numbered-formal', mainCategory: 'مستندات قانونية وتفويضات', subCategory: 'مالك', mainCategoryCode: 'LEG-01', subCategoryCode: 'LEG-01-04', defaultBlocks: [] },
  { id: 'doc-100', legacyNo: '100', code: 'DOC-100', internalCode: 'INT-100', name: 'عقد تفويض المالك للمقاول المنفذ', description: 'عقد تفويض', defaultSize: 'A4', defaultOrientation: 'portrait', supportedModes: ['manual', 'auto'], category: 'مستندات قانونية وتفويضات', subcategory: 'مالك', supportsGeneration: true, supportsCopy: true, supportsAI: false, readinessLevel: 'عالية', improvementStatus: 'مستقر', priority: 'عالية', usageCount: 0, lastUsedAt: '2026-04-05', officialCode: '100', officialCodeMode: 'numeric', officeCode: '1100', officeCodeMode: 'numeric', codeDisplayPriority: 'official', documentStyle: 'official-numbered-formal', mainCategory: 'مستندات قانونية وتفويضات', subCategory: 'مالك', mainCategoryCode: 'LEG-01', subCategoryCode: 'LEG-01-05', defaultBlocks: [] },
  { id: 'doc-101', legacyNo: '101', code: 'DOC-101', internalCode: 'INT-101', name: 'خطاب او وثيقة تحديد نوع المواد المخزنة داخل المستودعات', description: 'تحديد مواد', defaultSize: 'A4', defaultOrientation: 'portrait', supportedModes: ['manual', 'auto'], category: 'مستندات فنية', subcategory: 'مستودعات', supportsGeneration: true, supportsCopy: true, supportsAI: false, readinessLevel: 'متوسطة', improvementStatus: 'تحت التطوير', priority: 'متوسطة', usageCount: 0, lastUsedAt: '2026-04-05', officialCode: '101', officialCodeMode: 'numeric', officeCode: '1101', officeCodeMode: 'numeric', codeDisplayPriority: 'official', documentStyle: 'official-numbered-formal', mainCategory: 'مستندات فنية', subCategory: 'مستودعات', mainCategoryCode: 'TECH-01', subCategoryCode: 'TECH-01-02', defaultBlocks: [] },
  { id: 'doc-102', legacyNo: '102', code: 'DOC-102', internalCode: 'INT-102', name: 'المخطط الكهربائي', description: 'مخطط كهربائي', defaultSize: 'A3', defaultOrientation: 'landscape', supportedModes: ['manual', 'auto', 'ai'], category: 'مستندات المخططات', subcategory: 'كهرباء', supportsGeneration: true, supportsCopy: true, supportsAI: true, readinessLevel: 'عالية', improvementStatus: 'مستقر', priority: 'عالية', usageCount: 0, lastUsedAt: '2026-04-05', officialCode: '102', officialCodeMode: 'numeric', officeCode: '1102', officeCodeMode: 'numeric', codeDisplayPriority: 'official', documentStyle: 'official-numbered-formal', mainCategory: 'مستندات المخططات', subCategory: 'كهرباء', mainCategoryCode: 'PLAN-01', subCategoryCode: 'PLAN-01-05', defaultBlocks: [] },
  { id: 'doc-103', legacyNo: '103', code: 'DOC-103', internalCode: 'INT-103', name: 'المخطط الانشائي', description: 'مخطط إنشائي', defaultSize: 'A3', defaultOrientation: 'landscape', supportedModes: ['manual', 'auto', 'ai'], category: 'مستندات المخططات', subcategory: 'إنشائي', supportsGeneration: true, supportsCopy: true, supportsAI: true, readinessLevel: 'عالية', improvementStatus: 'مستقر', priority: 'عالية', usageCount: 0, lastUsedAt: '2026-04-05', officialCode: '103', officialCodeMode: 'numeric', officeCode: '1103', officeCodeMode: 'numeric', codeDisplayPriority: 'official', documentStyle: 'official-numbered-formal', mainCategory: 'مستندات المخططات', subCategory: 'إنشائي', mainCategoryCode: 'PLAN-01', subCategoryCode: 'PLAN-01-06', defaultBlocks: [] },
  { id: 'doc-104', legacyNo: '104', code: 'DOC-104', internalCode: 'INT-104', name: 'نموذج الرخص الفورية', description: 'رخص فورية', defaultSize: 'A4', defaultOrientation: 'portrait', supportedModes: ['manual', 'auto'], category: 'مستندات إدارية ومساندة', subcategory: 'نماذج', supportsGeneration: true, supportsCopy: true, supportsAI: false, readinessLevel: 'عالية', improvementStatus: 'مستقر', priority: 'عالية', usageCount: 0, lastUsedAt: '2026-04-05', officialCode: '104', officialCodeMode: 'numeric', officeCode: '1104', officeCodeMode: 'numeric', codeDisplayPriority: 'official', documentStyle: 'official-numbered-formal', mainCategory: 'مستندات إدارية ومساندة', subCategory: 'نماذج', mainCategoryCode: 'ADMIN-01', subCategoryCode: 'ADMIN-01-08', defaultBlocks: [] },
  { id: 'doc-105', legacyNo: '105', code: 'DOC-105', internalCode: 'INT-105', name: 'نموذج 9 - 10', description: 'نموذج 9-10', defaultSize: 'A4', defaultOrientation: 'portrait', supportedModes: ['manual', 'auto'], category: 'مستندات نماذج وتعهدات', subcategory: 'إداري', supportsGeneration: true, supportsCopy: true, supportsAI: false, readinessLevel: 'عالية', improvementStatus: 'مستقر', priority: 'عالية', usageCount: 0, lastUsedAt: '2026-04-05', officialCode: '105', officialCodeMode: 'numeric', officeCode: '1105', officeCodeMode: 'numeric', codeDisplayPriority: 'official', documentStyle: 'official-numbered-formal', mainCategory: 'مستندات نماذج وتعهدات', subCategory: 'إداري', mainCategoryCode: 'FORM-01', subCategoryCode: 'FORM-01-05', defaultBlocks: [] },
  { id: 'doc-106', legacyNo: '106', code: 'DOC-106', internalCode: 'INT-106', name: 'رخصة هدم', description: 'رخصة هدم', defaultSize: 'A4', defaultOrientation: 'portrait', supportedModes: ['manual', 'auto'], category: 'مستندات إدارية ومساندة', subcategory: 'هدم', supportsGeneration: true, supportsCopy: true, supportsAI: false, readinessLevel: 'عالية', improvementStatus: 'مستقر', priority: 'عالية', usageCount: 0, lastUsedAt: '2026-04-05', officialCode: '106', officialCodeMode: 'numeric', officeCode: '1106', officeCodeMode: 'numeric', codeDisplayPriority: 'official', documentStyle: 'official-numbered-formal', mainCategory: 'مستندات إدارية ومساندة', subCategory: 'هدم', mainCategoryCode: 'ADMIN-01', subCategoryCode: 'ADMIN-01-09', defaultBlocks: [] },
  { id: 'doc-107', legacyNo: '107', code: 'DOC-107', internalCode: 'INT-107', name: 'مخططات كفاءة الطاقة', description: 'مخطط طاقة', defaultSize: 'A3', defaultOrientation: 'landscape', supportedModes: ['manual', 'auto', 'ai'], category: 'مستندات المخططات', subcategory: 'طاقة', supportsGeneration: true, supportsCopy: true, supportsAI: true, readinessLevel: 'متوسطة', improvementStatus: 'تحت التطوير', priority: 'متوسطة', usageCount: 0, lastUsedAt: '2026-04-05', officialCode: '107', officialCodeMode: 'numeric', officeCode: '1107', officeCodeMode: 'numeric', codeDisplayPriority: 'official', documentStyle: 'official-numbered-formal', mainCategory: 'مستندات المخططات', subCategory: 'طاقة', mainCategoryCode: 'PLAN-01', subCategoryCode: 'PLAN-01-07', defaultBlocks: [] },
  { id: 'doc-108', legacyNo: '108', code: 'DOC-108', internalCode: 'INT-108', name: 'المخططات الميكانيكية', description: 'مخطط ميكانيكي', defaultSize: 'A3', defaultOrientation: 'landscape', supportedModes: ['manual', 'auto', 'ai'], category: 'مخططات', subcategory: 'ميكانيكا', supportsGeneration: true, supportsCopy: true, supportsAI: true, readinessLevel: 'عالية', improvementStatus: 'مستقر', priority: 'عالية', usageCount: 0, lastUsedAt: '2026-04-05', officialCode: '108', officialCodeMode: 'numeric', officeCode: '1108', officeCodeMode: 'numeric', codeDisplayPriority: 'official', documentStyle: 'official-numbered-formal', mainCategory: 'مستندات المخططات', subCategory: 'ميكانيكا', mainCategoryCode: 'PLAN-01', subCategoryCode: 'PLAN-01-08', defaultBlocks: [] },
  { id: 'doc-109', legacyNo: '109', code: 'DOC-109', internalCode: 'INT-109', name: 'شهادة اعتماد المكتب في بوابة بلدي', description: 'اعتماد بلدي', defaultSize: 'A4', defaultOrientation: 'portrait', supportedModes: ['manual'], category: 'مستندات شهادات واعتمادات', subcategory: 'اعتماد', supportsGeneration: false, supportsCopy: true, supportsAI: false, readinessLevel: 'عالية', improvementStatus: 'مستقر', priority: 'عالية', usageCount: 0, lastUsedAt: '2026-04-05', officialCode: '109', officialCodeMode: 'numeric', officeCode: '1109', officeCodeMode: 'numeric', codeDisplayPriority: 'official', documentStyle: 'official-numbered-formal', mainCategory: 'مستندات شهادات واعتمادات', subCategory: 'اعتماد', mainCategoryCode: 'CERT-01', subCategoryCode: 'CERT-01-03', defaultBlocks: [] },
  { id: 'doc-110', legacyNo: '110', code: 'DOC-110', internalCode: 'INT-110', name: 'شهادة المطابقة من هيئة تطوير المنطقة', description: 'شهادة مطابقة', defaultSize: 'A4', defaultOrientation: 'portrait', supportedModes: ['manual'], category: 'مستندات شهادات واعتمادات', subcategory: 'اعتماد', supportsGeneration: false, supportsCopy: true, supportsAI: false, readinessLevel: 'عالية', improvementStatus: 'مستقر', priority: 'عالية', usageCount: 0, lastUsedAt: '2026-04-05', officialCode: '110', officialCodeMode: 'numeric', officeCode: '1110', officeCodeMode: 'numeric', codeDisplayPriority: 'official', documentStyle: 'official-numbered-formal', mainCategory: 'مستندات شهادات واعتمادات', subCategory: 'اعتماد', mainCategoryCode: 'CERT-01', subCategoryCode: 'CERT-01-04', defaultBlocks: [] },
  { id: 'doc-111', legacyNo: '111', code: 'DOC-111', internalCode: 'INT-111', name: 'المخطط المعماري المعتمد من هيئة تطوير المنطقة', description: 'مخطط معماري', defaultSize: 'A3', defaultOrientation: 'landscape', supportedModes: ['manual'], category: 'مستندات المخططات', subcategory: 'اعتماد', supportsGeneration: false, supportsCopy: true, supportsAI: false, readinessLevel: 'عالية', improvementStatus: 'مستقر', priority: 'عالية', usageCount: 0, lastUsedAt: '2026-04-05', officialCode: '111', officialCodeMode: 'numeric', officeCode: '1111', officeCodeMode: 'numeric', codeDisplayPriority: 'official', documentStyle: 'official-numbered-formal', mainCategory: 'مستندات المخططات', subCategory: 'اعتماد', mainCategoryCode: 'PLAN-01', subCategoryCode: 'PLAN-01-09', defaultBlocks: [] },
  { id: 'doc-112', legacyNo: '112', code: 'DOC-112', internalCode: 'INT-112', name: 'نموذج مبدئي (مقترح) لتسوير ارض فضاء', description: 'نموذج تسوير', defaultSize: 'A4', defaultOrientation: 'portrait', supportedModes: ['manual', 'auto'], category: 'مستندات نماذج وتعهدات', subcategory: 'تسوير', supportsGeneration: true, supportsCopy: true, supportsAI: false, readinessLevel: 'متوسطة', improvementStatus: 'تحت التطوير', priority: 'متوسطة', usageCount: 0, lastUsedAt: '2026-04-05', officialCode: '112', officialCodeMode: 'numeric', officeCode: '1112', officeCodeMode: 'numeric', codeDisplayPriority: 'official', documentStyle: 'official-numbered-formal', mainCategory: 'مستندات نماذج وتعهدات', subCategory: 'تسوير', mainCategoryCode: 'FORM-01', subCategoryCode: 'FORM-01-06', defaultBlocks: [] },
  { id: 'doc-114', legacyNo: '114', code: 'DOC-114', internalCode: 'INT-114', name: 'شهادة العزل الحراري (الزامي للرخص الصادرة قبل 11/12/1442)', description: 'شهادة عزل', defaultSize: 'A4', defaultOrientation: 'portrait', supportedModes: ['manual', 'auto'], category: 'مستندات شهادات واعتمادات', subcategory: 'عزل', supportsGeneration: true, supportsCopy: true, supportsAI: false, readinessLevel: 'عالية', improvementStatus: 'مستقر', priority: 'عالية', usageCount: 0, lastUsedAt: '2026-04-05', officialCode: '114', officialCodeMode: 'numeric', officeCode: '1114', officeCodeMode: 'numeric', codeDisplayPriority: 'official', documentStyle: 'official-numbered-formal', mainCategory: 'مستندات شهادات واعتمادات', subCategory: 'عزل', mainCategoryCode: 'CERT-01', subCategoryCode: 'CERT-01-05', defaultBlocks: [] },
  { id: 'doc-115', legacyNo: '115', code: 'DOC-115', internalCode: 'INT-115', name: 'وكالة الورثة - لصاحب الصك المتوفى', description: 'وكالة ورثة', defaultSize: 'A4', defaultOrientation: 'portrait', supportedModes: ['manual'], category: 'مستندات قانونية وتفويضات', subcategory: 'ورثة', supportsGeneration: false, supportsCopy: true, supportsAI: false, readinessLevel: 'عالية', improvementStatus: 'مستقر', priority: 'عالية', usageCount: 0, lastUsedAt: '2026-04-05', officialCode: '115', officialCodeMode: 'numeric', officeCode: '1115', officeCodeMode: 'numeric', codeDisplayPriority: 'official', documentStyle: 'official-numbered-formal', mainCategory: 'مستندات قانونية وتفويضات', subCategory: 'ورثة', mainCategoryCode: 'LEG-01', subCategoryCode: 'LEG-01-06', defaultBlocks: [] },
  { id: 'doc-116', legacyNo: '116', code: 'DOC-116', internalCode: 'INT-116', name: 'صورة المصور الجوي', description: 'مصور جوي', defaultSize: 'A4', defaultOrientation: 'portrait', supportedModes: ['manual'], category: 'مستندات مساحية', subcategory: 'صور', supportsGeneration: false, supportsCopy: true, supportsAI: false, readinessLevel: 'عالية', improvementStatus: 'مستقر', priority: 'عالية', usageCount: 0, lastUsedAt: '2026-04-05', officialCode: '116', officialCodeMode: 'numeric', officeCode: '1116', officeCodeMode: 'numeric', codeDisplayPriority: 'official', documentStyle: 'official-numbered-formal', mainCategory: 'مستندات مساحية', subCategory: 'صور', mainCategoryCode: 'SURV-01', subCategoryCode: 'SURV-01-11', defaultBlocks: [] },
  { id: 'doc-117', legacyNo: '117', code: 'DOC-117', internalCode: 'INT-117', name: 'صورة من الطبيعة', description: 'صورة طبيعة', defaultSize: 'A4', defaultOrientation: 'portrait', supportedModes: ['manual'], category: 'مستندات مساحية', subcategory: 'صور', supportsGeneration: false, supportsCopy: true, supportsAI: false, readinessLevel: 'عالية', improvementStatus: 'مستقر', priority: 'عالية', usageCount: 0, lastUsedAt: '2026-04-05', officialCode: '117', officialCodeMode: 'numeric', officeCode: '1117', officeCodeMode: 'numeric', codeDisplayPriority: 'official', documentStyle: 'official-numbered-formal', mainCategory: 'مستندات مساحية', subCategory: 'صور', mainCategoryCode: 'SURV-01', subCategoryCode: 'SURV-01-12', defaultBlocks: [] },
  { id: 'doc-118', legacyNo: '118', code: 'DOC-118', internalCode: 'INT-118', name: 'عقد الايجار الاستثماري بين المالك والمستثمر', description: 'عقد إيجار', defaultSize: 'A4', defaultOrientation: 'portrait', supportedModes: ['manual'], category: 'مستندات قانونية وتفويضات', subcategory: 'استثمار', supportsGeneration: false, supportsCopy: true, supportsAI: false, readinessLevel: 'عالية', improvementStatus: 'مستقر', priority: 'عالية', usageCount: 0, lastUsedAt: '2026-04-05', officialCode: '118', officialCodeMode: 'numeric', officeCode: '1118', officeCodeMode: 'numeric', codeDisplayPriority: 'official', documentStyle: 'official-numbered-formal', mainCategory: 'مستندات قانونية وتفويضات', subCategory: 'استثمار', mainCategoryCode: 'LEG-01', subCategoryCode: 'LEG-01-07', defaultBlocks: [] },
  { id: 'doc-119', legacyNo: '119', code: 'DOC-119', internalCode: 'INT-119', name: 'ملاحظات ادارة كود المدينة', description: 'ملاحظات كود', defaultSize: 'A4', defaultOrientation: 'portrait', supportedModes: ['manual', 'auto'], category: 'مستندات فنية', subcategory: 'كود', supportsGeneration: true, supportsCopy: true, supportsAI: false, readinessLevel: 'متوسطة', improvementStatus: 'تحت التطوير', priority: 'متوسطة', usageCount: 0, lastUsedAt: '2026-04-05', officialCode: '119', officialCodeMode: 'numeric', officeCode: '1119', officeCodeMode: 'numeric', codeDisplayPriority: 'official', documentStyle: 'official-numbered-formal', mainCategory: 'مستندات فنية', subCategory: 'كود', mainCategoryCode: 'TECH-01', subCategoryCode: 'TECH-01-03', defaultBlocks: [] },
  { id: 'doc-120', legacyNo: '120', code: 'DOC-120', internalCode: 'INT-120', name: 'شهادة عدم الممانعة متطلب الزامي', description: 'شهادة عدم ممانعة', defaultSize: 'A4', defaultOrientation: 'portrait', supportedModes: ['manual', 'auto'], category: 'مستندات شهادات واعتمادات', subcategory: 'ممانعة', supportsGeneration: true, supportsCopy: true, supportsAI: false, readinessLevel: 'عالية', improvementStatus: 'مستقر', priority: 'عالية', usageCount: 0, lastUsedAt: '2026-04-05', officialCode: '120', officialCodeMode: 'numeric', officeCode: '1120', officeCodeMode: 'numeric', codeDisplayPriority: 'official', documentStyle: 'official-numbered-formal', mainCategory: 'مستندات شهادات واعتمادات', subCategory: 'ممانعة', mainCategoryCode: 'CERT-01', subCategoryCode: 'CERT-01-06', defaultBlocks: [] },
  { id: 'doc-121', legacyNo: '121', code: 'DOC-121', internalCode: 'INT-121', name: 'رفع مساحي للموقع بالاحداثيات', description: 'رفع مساحي', defaultSize: 'A3', defaultOrientation: 'landscape', supportedModes: ['manual', 'auto', 'ai'], category: 'مستندات مساحية', subcategory: 'تقارير', supportsGeneration: true, supportsCopy: true, supportsAI: true, readinessLevel: 'عالية', improvementStatus: 'مستقر', priority: 'عالية', usageCount: 0, lastUsedAt: '2026-04-05', officialCode: '121', officialCodeMode: 'numeric', officeCode: '1121', officeCodeMode: 'numeric', codeDisplayPriority: 'official', documentStyle: 'official-numbered-formal', mainCategory: 'مستندات مساحية', subCategory: 'تقارير', mainCategoryCode: 'SURV-01', subCategoryCode: 'SURV-01-13', defaultBlocks: [] },
  { id: 'doc-122', legacyNo: '122', code: 'DOC-122', internalCode: 'INT-122', name: 'صك ناظر وقف', description: 'صك وقف', defaultSize: 'A4', defaultOrientation: 'portrait', supportedModes: ['manual'], category: 'مستندات ملكية وهوية', subcategory: 'وقف', supportsGeneration: false, supportsCopy: true, supportsAI: false, readinessLevel: 'عالية', improvementStatus: 'مستقر', priority: 'عالية', usageCount: 0, lastUsedAt: '2026-04-05', officialCode: '122', officialCodeMode: 'numeric', officeCode: '1122', officeCodeMode: 'numeric', codeDisplayPriority: 'official', documentStyle: 'official-numbered-formal', mainCategory: 'مستندات ملكية وهوية', subCategory: 'وقف', mainCategoryCode: 'PROP-01', subCategoryCode: 'PROP-01-01', defaultBlocks: [] },
  { id: 'doc-123', legacyNo: '123', code: 'DOC-123', internalCode: 'INT-123', name: 'نظام البناء المعتمد من ادارة الرخص', description: 'نظام بناء', defaultSize: 'A4', defaultOrientation: 'portrait', supportedModes: ['manual'], category: 'مستندات إدارية ومساندة', subcategory: 'أنظمة', supportsGeneration: false, supportsCopy: true, supportsAI: false, readinessLevel: 'عالية', improvementStatus: 'مستقر', priority: 'عالية', usageCount: 0, lastUsedAt: '2026-04-05', officialCode: '123', officialCodeMode: 'numeric', officeCode: '1123', officeCodeMode: 'numeric', codeDisplayPriority: 'official', documentStyle: 'official-numbered-formal', mainCategory: 'مستندات إدارية ومساندة', subCategory: 'أنظمة', mainCategoryCode: 'ADMIN-01', subCategoryCode: 'ADMIN-01-10', defaultBlocks: [] },
  { id: 'doc-124', legacyNo: '124', code: 'DOC-124', internalCode: 'INT-124', name: 'الرسومات التنفيذية لمظلة السيارات', description: 'رسومات مظلة', defaultSize: 'A3', defaultOrientation: 'landscape', supportedModes: ['manual', 'auto'], category: 'مستندات المخططات', subcategory: 'مظلات', supportsGeneration: true, supportsCopy: true, supportsAI: false, readinessLevel: 'متوسطة', improvementStatus: 'تحت التطوير', priority: 'متوسطة', usageCount: 0, lastUsedAt: '2026-04-05', officialCode: '124', officialCodeMode: 'numeric', officeCode: '1124', officeCodeMode: 'numeric', codeDisplayPriority: 'official', documentStyle: 'official-numbered-formal', mainCategory: 'مستندات المخططات', subCategory: 'مظلات', mainCategoryCode: 'PLAN-01', subCategoryCode: 'PLAN-01-10', defaultBlocks: [] },
  { id: 'doc-125', legacyNo: '125', code: 'DOC-125', internalCode: 'INT-125', name: 'شهادة تسجيل وقف', description: 'شهادة وقف', defaultSize: 'A4', defaultOrientation: 'portrait', supportedModes: ['manual'], category: 'مستندات شهادات واعتمادات', subcategory: 'وقف', supportsGeneration: false, supportsCopy: true, supportsAI: false, readinessLevel: 'عالية', improvementStatus: 'مستقر', priority: 'عالية', usageCount: 0, lastUsedAt: '2026-04-05', officialCode: '125', officialCodeMode: 'numeric', officeCode: '1125', officeCodeMode: 'numeric', codeDisplayPriority: 'official', documentStyle: 'official-numbered-formal', mainCategory: 'مستندات شهادات واعتمادات', subCategory: 'وقف', mainCategoryCode: 'CERT-01', subCategoryCode: 'CERT-01-07', defaultBlocks: [] },
  { id: 'doc-126', legacyNo: '126', code: 'DOC-126', internalCode: 'INT-126', name: 'التقسيم المقترح للارض المراد تجزئتها', description: 'تقسيم مقترح', defaultSize: 'A3', defaultOrientation: 'landscape', supportedModes: ['manual', 'auto'], category: 'مستندات مساحية', subcategory: 'مخططات', supportsGeneration: true, supportsCopy: true, supportsAI: false, readinessLevel: 'متوسطة', improvementStatus: 'تحت التطوير', priority: 'متوسطة', usageCount: 0, lastUsedAt: '2026-04-05', officialCode: '126', officialCodeMode: 'numeric', officeCode: '1126', officeCodeMode: 'numeric', codeDisplayPriority: 'official', documentStyle: 'official-numbered-formal', mainCategory: 'مستندات مساحية', subCategory: 'مخططات', mainCategoryCode: 'SURV-01', subCategoryCode: 'SURV-01-14', defaultBlocks: [] },
  { id: 'doc-128', legacyNo: '128', code: 'DOC-128', internalCode: 'INT-128', name: 'تقرير اختبار التربة', description: 'تقرير تربة', defaultSize: 'A4', defaultOrientation: 'portrait', supportedModes: ['manual', 'auto'], category: 'مستندات فنية', subcategory: 'تربة', supportsGeneration: true, supportsCopy: true, supportsAI: false, readinessLevel: 'عالية', improvementStatus: 'مستقر', priority: 'عالية', usageCount: 0, lastUsedAt: '2026-04-05', officialCode: '128', officialCodeMode: 'numeric', officeCode: '1128', officeCodeMode: 'numeric', codeDisplayPriority: 'official', documentStyle: 'official-numbered-formal', mainCategory: 'مستندات فنية', subCategory: 'تربة', mainCategoryCode: 'TECH-01', subCategoryCode: 'TECH-01-04', defaultBlocks: [] },
  { id: 'doc-129', legacyNo: '129', code: 'DOC-129', internalCode: 'INT-129', name: 'السجل العقاري', description: 'سجل عقاري', defaultSize: 'A4', defaultOrientation: 'portrait', supportedModes: ['manual'], category: 'مستندات ملكية وهوية', subcategory: 'سجل', supportsGeneration: false, supportsCopy: true, supportsAI: false, readinessLevel: 'عالية', improvementStatus: 'مستقر', priority: 'عالية', usageCount: 0, lastUsedAt: '2026-04-05', officialCode: '129', officialCodeMode: 'numeric', officeCode: '1129', officeCodeMode: 'numeric', codeDisplayPriority: 'official', documentStyle: 'official-numbered-formal', mainCategory: 'مستندات ملكية وهوية', subCategory: 'سجل', mainCategoryCode: 'PROP-01', subCategoryCode: 'PROP-01-02', defaultBlocks: [] },
  { id: 'doc-130', legacyNo: '130', code: 'DOC-130', internalCode: 'INT-130', name: 'مخطط للسور المؤقت اجباري', description: 'مخطط سور', defaultSize: 'A3', defaultOrientation: 'landscape', supportedModes: ['manual', 'auto'], category: 'مستندات المخططات', subcategory: 'تسوير', supportsGeneration: true, supportsCopy: true, supportsAI: false, readinessLevel: 'عالية', improvementStatus: 'مستقر', priority: 'عالية', usageCount: 0, lastUsedAt: '2026-04-05', officialCode: '130', officialCodeMode: 'numeric', officeCode: '1130', officeCodeMode: 'numeric', codeDisplayPriority: 'official', documentStyle: 'official-numbered-formal', mainCategory: 'مستندات المخططات', subCategory: 'تسوير', mainCategoryCode: 'PLAN-01', subCategoryCode: 'PLAN-01-11', defaultBlocks: [] },
  { id: 'doc-131', legacyNo: '131', code: 'DOC-131', internalCode: 'INT-131', name: 'شهادة التنسيق مع مشروع الرياض', description: 'شهادة تنسيق', defaultSize: 'A4', defaultOrientation: 'portrait', supportedModes: ['manual'], category: 'مستندات شهادات واعتمادات', subcategory: 'تنسيق', supportsGeneration: false, supportsCopy: true, supportsAI: false, readinessLevel: 'عالية', improvementStatus: 'مستقر', priority: 'عالية', usageCount: 0, lastUsedAt: '2026-04-05', officialCode: '131', officialCodeMode: 'numeric', officeCode: '1131', officeCodeMode: 'numeric', codeDisplayPriority: 'official', documentStyle: 'official-numbered-formal', mainCategory: 'مستندات شهادات واعتمادات', subCategory: 'تنسيق', mainCategoryCode: 'CERT-01', subCategoryCode: 'CERT-01-08', defaultBlocks: [] },
  { id: 'doc-132', legacyNo: '132', code: 'DOC-132', internalCode: 'INT-132', name: 'تعهد المكتب الهندسي المشرف', description: 'تعهد مشرف', defaultSize: 'A4', defaultOrientation: 'portrait', supportedModes: ['manual', 'auto'], category: 'مستندات نماذج وتعهدات', subcategory: 'هندسي', supportsGeneration: true, supportsCopy: true, supportsAI: false, readinessLevel: 'عالية', improvementStatus: 'مستقر', priority: 'عالية', usageCount: 0, lastUsedAt: '2026-04-05', officialCode: '132', officialCodeMode: 'numeric', officeCode: '1132', officeCodeMode: 'numeric', codeDisplayPriority: 'official', documentStyle: 'official-numbered-formal', mainCategory: 'مستندات نماذج وتعهدات', subCategory: 'هندسي', mainCategoryCode: 'FORM-01', subCategoryCode: 'FORM-01-07', defaultBlocks: [] },
  { id: 'doc-133', legacyNo: '133', code: 'DOC-133', internalCode: 'INT-133', name: 'تعهد بإغلاق فتحات خزانات المياه', description: 'تعهد إغلاق', defaultSize: 'A4', defaultOrientation: 'portrait', supportedModes: ['manual', 'auto'], category: 'مستندات نماذج وتعهدات', subcategory: 'خزانات', supportsGeneration: true, supportsCopy: true, supportsAI: false, readinessLevel: 'عالية', improvementStatus: 'مستقر', priority: 'عالية', usageCount: 0, lastUsedAt: '2026-04-05', officialCode: '133', officialCodeMode: 'numeric', officeCode: '1133', officeCodeMode: 'numeric', codeDisplayPriority: 'official', documentStyle: 'official-numbered-formal', mainCategory: 'مستندات نماذج وتعهدات', subCategory: 'خزانات', mainCategoryCode: 'FORM-01', subCategoryCode: 'FORM-01-08', defaultBlocks: [] },
  { id: 'doc-134', legacyNo: '134', code: 'DOC-134', internalCode: 'INT-134', name: 'مستند إطلاق تيار', description: 'مستند إطلاق تيار', defaultSize: 'A4', defaultOrientation: 'portrait', supportedModes: ['manual', 'auto'], category: 'مستندات فنية', subcategory: 'تشغيل', supportsGeneration: true, supportsCopy: true, supportsAI: false, readinessLevel: 'عالية', improvementStatus: 'مستقر', priority: 'عالية', usageCount: 0, lastUsedAt: '2026-04-05', officialCode: '134', officialCodeMode: 'numeric', officeCode: '1134', officeCodeMode: 'numeric', codeDisplayPriority: 'official', documentStyle: 'official-numbered-formal', mainCategory: 'مستندات فنية', subCategory: 'تشغيل', mainCategoryCode: 'TECH-01', subCategoryCode: 'TECH-01-05', defaultBlocks: [] },
  { id: 'meeting-minute', code: 'MM-001', internalCode: 'MEET-MIN-01', name: 'محضر اجتماع', description: 'توثيق لمحاضر الاجتماعات والمخرجات', defaultSize: 'A4', defaultOrientation: 'portrait', supportedModes: ['manual', 'auto', 'ai'], category: 'مستندات إدارية', subcategory: 'اجتماعات', supportsGeneration: true, supportsCopy: true, supportsAI: true, readinessLevel: 'عالية', improvementStatus: 'مستقر', priority: 'عالية', status: 'نشطة', usageCount: 0, lastUsedAt: '2026-04-05', officialCode: '401', officialCodeMode: 'numeric', officeCode: '1401', officeCodeMode: 'numeric', codeDisplayPriority: 'official', documentStyle: 'official-numbered-formal', mainCategory: 'مستندات إدارية', subCategory: 'اجتماعات', mainCategoryCode: 'ADM-02', subCategoryCode: 'ADM-02-01', defaultBlocks: [] },
  { id: 'financial-invoice', code: 'INV-001', internalCode: 'FIN-INV-01', name: 'فاتورة مالية', description: 'فاتورة ضريبية للأمور المالية', defaultSize: 'A4', defaultOrientation: 'portrait', supportedModes: ['manual', 'auto'], category: 'مستندات مالية', subcategory: 'فواتير', supportsGeneration: true, supportsCopy: true, supportsAI: false, readinessLevel: 'عالية', improvementStatus: 'مستقر', priority: 'عالية', status: 'نشطة', usageCount: 0, lastUsedAt: '2026-04-05', officialCode: '402', officialCodeMode: 'numeric', officeCode: '1402', officeCodeMode: 'numeric', codeDisplayPriority: 'official', documentStyle: 'official-numbered-formal', mainCategory: 'مستندات مالية', subCategory: 'فواتير', mainCategoryCode: 'FIN-01', subCategoryCode: 'FIN-01-01', defaultBlocks: [] },
  { id: 'contract', code: 'CTR-001', internalCode: 'CONTR-01', name: 'عقد اتفاق', description: 'عقد اتفاق بين الأطراف لضمان الحقوق', defaultSize: 'A4', defaultOrientation: 'portrait', supportedModes: ['manual', 'auto', 'ai'], category: 'مستندات قانونية', subcategory: 'عقود', supportsGeneration: true, supportsCopy: true, supportsAI: true, readinessLevel: 'عالية', improvementStatus: 'مستقر', priority: 'عالية', status: 'نشطة', usageCount: 0, lastUsedAt: '2026-04-05', officialCode: '403', officialCodeMode: 'numeric', officeCode: '1403', officeCodeMode: 'numeric', codeDisplayPriority: 'official', documentStyle: 'official-numbered-formal', mainCategory: 'مستندات قانونية', subCategory: 'عقود', mainCategoryCode: 'LEG-02', subCategoryCode: 'LEG-02-01', defaultBlocks: [] }
];

async function main() {
  console.log('🌱 جاري بدء عملية إدخال المستندات...');

  let successCount = 0;
  let skipCount = 0;
  let errorCount = 0;

  for (const doc of documentCatalog) {
    try {
      // 1. التحقق إذا كان المستند موجوداً مسبقاً (لتجنب تكرار كود)
      const existingDoc = await prisma.documentTemplate.findUnique({
        where: { code: doc.code }
      });

      if (existingDoc) {
        console.log(`⚠️ المستند ${doc.code} موجود مسبقاً، تم التخطي.`);
        skipCount++;
        continue;
      }

      // 2. تحويل البيانات (Mapping) لتتوافق مع Schema.prisma الخاص بك
      const docData = {
        title: doc.name, // في الكتالوج اسمها name، وفي الـ schema اسمها title
        code: doc.code,
        internalCode: doc.internalCode || null,
        category: doc.category || 'document',
        pageSize: doc.defaultSize || 'A4',
        orientation: doc.defaultOrientation || 'portrait',
        securityLevel: 'public', // قيم افتراضية آمنة
        sourceType: 'system',
        readinessLevel: doc.readinessLevel || 'مكتمل',
        status: doc.status || 'نشطة',
        aiEnabled: doc.supportsAI ?? true,
        // معالجة المصفوفات إلى JSON
        allowedSizes: ['A4', 'A3', 'A2', 'A1', 'A0'],
        allowedOrientations: ['portrait', 'landscape'],
        allowedExtensions: ['.pdf', '.docx', '.jpg', '.dwg'],
        // معالجة البلوكات إذا وجدت
        blocks: doc.defaultBlocks ? doc.defaultBlocks.map(b => ({
           name: b.label || b.id,
           type: b.type || 'text',
           mandatory: b.required || false,
           aiSupport: b.aiSupport || false
        })) : [],
        // معلومات إضافية نضعها في النوتس الداخلية
        internalNotes: doc.description || null
      };

      // 3. الإدخال الفعلي
      await prisma.documentTemplate.create({
        data: docData
      });

      console.log(`✅ تم إدخال: ${doc.name} (${doc.code})`);
      successCount++;
    } catch (error) {
      console.error(`❌ خطأ في إدخال ${doc.code}:`, error.message);
      errorCount++;
    }
  }

  console.log('\n📊 --- ملخص العملية ---');
  console.log(`نجاح: ${successCount}`);
  console.log(`تخطي: ${skipCount}`);
  console.log(`فشل: ${errorCount}`);
}

main()
  .catch((e) => {
    console.error('حدث خطأ غير متوقع:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
    console.log('🔌 تم إغلاق الاتصال بقاعدة البيانات.');
  });